module Courier
  module Models
    module Tenants
      module DefaultPreferences
        type channel_classification =
          :direct_message | :email | :push | :sms | :webhook | :inbox

        module ChannelClassification
          extend Courier::Internal::Type::Enum

          DIRECT_MESSAGE: :direct_message
          EMAIL: :email
          PUSH: :push
          SMS: :sms
          WEBHOOK: :webhook
          INBOX: :inbox

          def self?.values: -> ::Array[Courier::Models::Tenants::DefaultPreferences::channel_classification]
        end
      end
    end
  end
end
