module Courier
  module Models
    module Tenants
      module DefaultPreferences
        type item_update_params =
          { tenant_id: String } & Courier::Internal::Type::request_parameters

        class ItemUpdateParams < Courier::Models::Tenants::DefaultPreferences::SubscriptionTopicNew
          extend Courier::Internal::Type::RequestParameters::Converter
          include Courier::Internal::Type::RequestParameters

          def tenant_id: -> String

          def tenant_id=: (String _) -> String

          def initialize: (
            tenant_id: String,
            ?request_options: Courier::request_opts
          ) -> void

          def to_hash: -> {
            tenant_id: String,
            request_options: Courier::RequestOptions
          }
        end
      end
    end
  end
end
