module Trycourier
  module Models
    module Lists
      type subscription_unsubscribe_user_params =
        { list_id: String } & Trycourier::Internal::Type::request_parameters

      class SubscriptionUnsubscribeUserParams < Trycourier::Internal::Type::BaseModel
        extend Trycourier::Internal::Type::RequestParameters::Converter
        include Trycourier::Internal::Type::RequestParameters

        attr_accessor list_id: String

        def initialize: (
          list_id: String,
          ?request_options: Trycourier::request_opts
        ) -> void

        def to_hash: -> {
          list_id: String,
          request_options: Trycourier::RequestOptions
        }
      end
    end
  end
end
