module Trycourier
  module Resources
    class Tenants
      class Preferences
        attr_reader items: Trycourier::Resources::Tenants::Preferences::Items

        def initialize: (client: Trycourier::Client) -> void
      end
    end
  end
end
