module Trycourier
  module Resources
    class Tenants
      class Templates
        def retrieve: (
          String template_id,
          tenant_id: String,
          ?request_options: Trycourier::request_opts
        ) -> Trycourier::BaseTemplateTenantAssociation

        def list: (
          String tenant_id,
          ?cursor: String?,
          ?limit: Integer?,
          ?request_options: Trycourier::request_opts
        ) -> Trycourier::Models::Tenants::TemplateListResponse

        def initialize: (client: Trycourier::Client) -> void
      end
    end
  end
end
