module Trycourier
  module Resources
    class Tenants
      class TenantDefaultPreferences
        attr_reader items: Trycourier::Resources::Tenants::TenantDefaultPreferences::Items

        def initialize: (client: Trycourier::Client) -> void
      end
    end
  end
end
