module Trycourier
  module Resources
    class Bulk
      def add_users: (
        String job_id,
        users: ::Array[Trycourier::InboundBulkMessageUser],
        ?request_options: Trycourier::request_opts
      ) -> nil

      def create_job: (
        message: Trycourier::InboundBulkMessage,
        ?request_options: Trycourier::request_opts
      ) -> Trycourier::Models::BulkCreateJobResponse

      def list_users: (
        String job_id,
        ?cursor: String?,
        ?request_options: Trycourier::request_opts
      ) -> Trycourier::Models::BulkListUsersResponse

      def retrieve_job: (
        String job_id,
        ?request_options: Trycourier::request_opts
      ) -> Trycourier::Models::BulkRetrieveJobResponse

      def run_job: (
        String job_id,
        ?request_options: Trycourier::request_opts
      ) -> nil

      def initialize: (client: Trycourier::Client) -> void
    end
  end
end
