module Trycourier
  module Resources
    class Notifications
      attr_reader draft: Trycourier::Resources::Notifications::Draft

      attr_reader checks: Trycourier::Resources::Notifications::Checks

      def list: (
        ?cursor: String?,
        ?notes: bool?,
        ?request_options: Trycourier::request_opts
      ) -> Trycourier::Models::NotificationListResponse

      def retrieve_content: (
        String id,
        ?request_options: Trycourier::request_opts
      ) -> Trycourier::NotificationGetContent

      def initialize: (client: Trycourier::Client) -> void
    end
  end
end
