module Trycourier
  module Resources
    class Tenants
      attr_reader default_preferences: Trycourier::Resources::Tenants::DefaultPreferences

      attr_reader templates: Trycourier::Resources::Tenants::Templates

      def retrieve: (
        String tenant_id,
        ?request_options: Trycourier::request_opts
      ) -> Trycourier::Tenant

      def update: (
        String tenant_id,
        name: String,
        ?brand_id: String?,
        ?default_preferences: Trycourier::DefaultPreferences?,
        ?parent_tenant_id: String?,
        ?properties: ::Hash[Symbol, top]?,
        ?user_profile: ::Hash[Symbol, top]?,
        ?request_options: Trycourier::request_opts
      ) -> Trycourier::Tenant

      def list: (
        ?cursor: String?,
        ?limit: Integer?,
        ?parent_tenant_id: String?,
        ?request_options: Trycourier::request_opts
      ) -> Trycourier::Models::TenantListResponse

      def delete: (
        String tenant_id,
        ?request_options: Trycourier::request_opts
      ) -> nil

      def list_users: (
        String tenant_id,
        ?cursor: String?,
        ?limit: Integer?,
        ?request_options: Trycourier::request_opts
      ) -> Trycourier::Models::TenantListUsersResponse

      def initialize: (client: Trycourier::Client) -> void
    end
  end
end
