module Trycourier
  module Resources
    class Automations
      class Invoke
        def invoke_ad_hoc: (
          automation: Trycourier::Automations::InvokeInvokeAdHocParams::Automation,
          ?brand: String?,
          ?data: ::Hash[Symbol, top]?,
          ?profile: ::Hash[Symbol, top]?,
          ?recipient: String?,
          ?template: String?,
          ?request_options: Trycourier::request_opts
        ) -> Trycourier::AutomationInvokeResponse

        def invoke_by_template: (
          String template_id,
          recipient: String?,
          ?brand: String?,
          ?data: ::Hash[Symbol, top]?,
          ?profile: ::Hash[Symbol, top]?,
          ?template: String?,
          ?request_options: Trycourier::request_opts
        ) -> Trycourier::AutomationInvokeResponse

        def initialize: (client: Trycourier::Client) -> void
      end
    end
  end
end
