module Courier
  module Models
    module Digests
      type schedule_list_instances_params =
        { schedule_id: String, cursor: String, limit: Integer }
        & Courier::Internal::Type::request_parameters

      class ScheduleListInstancesParams < Courier::Internal::Type::BaseModel
        extend Courier::Internal::Type::RequestParameters::Converter
        include Courier::Internal::Type::RequestParameters

        attr_accessor schedule_id: String

        attr_reader cursor: String?

        def cursor=: (String) -> String

        attr_reader limit: Integer?

        def limit=: (Integer) -> Integer

        def initialize: (
          schedule_id: String,
          ?cursor: String,
          ?limit: Integer,
          ?request_options: Courier::request_opts
        ) -> void

        def to_hash: -> {
          schedule_id: String,
          cursor: String,
          limit: Integer,
          request_options: Courier::RequestOptions
        }
      end
    end
  end
end
