module Courier
  module Resources
    class Journeys
      class Templates
        def create: (
          String template_id,
          channel: String,
          notification: Courier::JourneyTemplateCreateRequest::Notification,
          ?provider_key: String,
          ?state: String,
          ?request_options: Courier::request_opts
        ) -> Courier::JourneyTemplateGetResponse

        def retrieve: (
          String notification_id,
          template_id: String,
          ?request_options: Courier::request_opts
        ) -> Courier::JourneyTemplateGetResponse

        def list: (
          String template_id,
          ?cursor: String,
          ?limit: Integer,
          ?request_options: Courier::request_opts
        ) -> Courier::JourneyTemplateListResponse

        def archive: (
          String notification_id,
          template_id: String,
          ?request_options: Courier::request_opts
        ) -> nil

        def list_versions: (
          String notification_id,
          template_id: String,
          ?request_options: Courier::request_opts
        ) -> Courier::NotificationTemplateVersionListResponse

        def publish: (
          String notification_id,
          template_id: String,
          ?version: String,
          ?request_options: Courier::request_opts
        ) -> nil

        def put_content: (
          String notification_id,
          template_id: String,
          content: Courier::NotificationContentPutRequest::Content,
          ?state: Courier::Models::notification_template_state,
          ?request_options: Courier::request_opts
        ) -> Courier::NotificationContentMutationResponse

        def put_locale: (
          String locale_id,
          template_id: String,
          notification_id: String,
          elements: ::Array[Courier::NotificationLocalePutRequest::Element],
          ?state: Courier::Models::notification_template_state,
          ?request_options: Courier::request_opts
        ) -> Courier::NotificationContentMutationResponse

        def replace: (
          String notification_id,
          template_id: String,
          notification: Courier::JourneyTemplateReplaceRequest::Notification,
          ?state: String,
          ?request_options: Courier::request_opts
        ) -> Courier::JourneyTemplateGetResponse

        def retrieve_content: (
          String notification_id,
          template_id: String,
          ?version: String,
          ?request_options: Courier::request_opts
        ) -> Courier::NotificationContentGetResponse

        def initialize: (client: Courier::Client) -> void
      end
    end
  end
end
