module Trycourier
  module Models
    type audience =
      {
        id: String,
        created_at: String,
        description: String,
        name: String,
        updated_at: String,
        filter: Trycourier::Filter?,
        operator: Trycourier::Models::Audience::operator
      }

    class Audience < Trycourier::Internal::Type::BaseModel
      attr_accessor id: String

      attr_accessor created_at: String

      attr_accessor description: String

      attr_accessor name: String

      attr_accessor updated_at: String

      attr_accessor filter: Trycourier::Filter?

      attr_reader operator: Trycourier::Models::Audience::operator?

      def operator=: (
        Trycourier::Models::Audience::operator
      ) -> Trycourier::Models::Audience::operator

      def initialize: (
        id: String,
        created_at: String,
        description: String,
        name: String,
        updated_at: String,
        ?filter: Trycourier::Filter?,
        ?operator: Trycourier::Models::Audience::operator
      ) -> void

      def to_hash: -> {
        id: String,
        created_at: String,
        description: String,
        name: String,
        updated_at: String,
        filter: Trycourier::Filter?,
        operator: Trycourier::Models::Audience::operator
      }

      type operator = :AND | :OR

      module Operator
        extend Trycourier::Internal::Type::Enum

        AND: :AND
        OR: :OR

        def self?.values: -> ::Array[Trycourier::Models::Audience::operator]
      end
    end
  end
end
