module Trycourier
  module Models
    type audience =
      {
        id: String,
        created_at: String,
        description: String,
        filter: Trycourier::Models::filter,
        name: String,
        updated_at: String
      }

    class Audience < Trycourier::Internal::Type::BaseModel
      attr_accessor id: String

      attr_accessor created_at: String

      attr_accessor description: String

      attr_accessor filter: Trycourier::Models::filter

      attr_accessor name: String

      attr_accessor updated_at: String

      def initialize: (
        id: String,
        created_at: String,
        description: String,
        filter: Trycourier::Models::filter,
        name: String,
        updated_at: String
      ) -> void

      def to_hash: -> {
        id: String,
        created_at: String,
        description: String,
        filter: Trycourier::Models::filter,
        name: String,
        updated_at: String
      }
    end
  end
end
