module Trycourier
  module Models
    type audience_update_params =
      {
        description: String?,
        filter: Trycourier::AudienceFilterConfig?,
        name: String?,
        operator: Trycourier::Models::AudienceUpdateParams::operator?
      }
      & Trycourier::Internal::Type::request_parameters

    class AudienceUpdateParams < Trycourier::Internal::Type::BaseModel
      extend Trycourier::Internal::Type::RequestParameters::Converter
      include Trycourier::Internal::Type::RequestParameters

      attr_accessor description: String?

      attr_accessor filter: Trycourier::AudienceFilterConfig?

      attr_accessor name: String?

      attr_accessor operator: Trycourier::Models::AudienceUpdateParams::operator?

      def initialize: (
        ?description: String?,
        ?filter: Trycourier::AudienceFilterConfig?,
        ?name: String?,
        ?operator: Trycourier::Models::AudienceUpdateParams::operator?,
        ?request_options: Trycourier::request_opts
      ) -> void

      def to_hash: -> {
        description: String?,
        filter: Trycourier::AudienceFilterConfig?,
        name: String?,
        operator: Trycourier::Models::AudienceUpdateParams::operator?,
        request_options: Trycourier::RequestOptions
      }

      type operator = :AND | :OR

      module Operator
        extend Trycourier::Internal::Type::Enum

        AND: :AND
        OR: :OR

        def self?.values: -> ::Array[Trycourier::Models::AudienceUpdateParams::operator]
      end
    end
  end
end
