module Trycourier
  module Models
    type audit_event_list_response =
      { paging: Trycourier::Paging, results: ::Array[Trycourier::AuditEvent] }

    class AuditEventListResponse < Trycourier::Internal::Type::BaseModel
      attr_accessor paging: Trycourier::Paging

      attr_accessor results: ::Array[Trycourier::AuditEvent]

      def initialize: (
        paging: Trycourier::Paging,
        results: ::Array[Trycourier::AuditEvent]
      ) -> void

      def to_hash: -> {
        paging: Trycourier::Paging,
        results: ::Array[Trycourier::AuditEvent]
      }
    end
  end
end
