module Trycourier
  module Models
    type auth_issue_token_params =
      { expires_in: String, scope: String }
      & Trycourier::Internal::Type::request_parameters

    class AuthIssueTokenParams < Trycourier::Internal::Type::BaseModel
      extend Trycourier::Internal::Type::RequestParameters::Converter
      include Trycourier::Internal::Type::RequestParameters

      attr_accessor expires_in: String

      attr_accessor scope: String

      def initialize: (
        expires_in: String,
        scope: String,
        ?request_options: Trycourier::request_opts
      ) -> void

      def to_hash: -> {
        expires_in: String,
        scope: String,
        request_options: Trycourier::RequestOptions
      }
    end
  end
end
