module Trycourier
  module Models
    type base_template_tenant_association =
      {
        id: String,
        created_at: String,
        published_at: String,
        updated_at: String,
        version: String
      }

    class BaseTemplateTenantAssociation < Trycourier::Internal::Type::BaseModel
      attr_accessor id: String

      attr_accessor created_at: String

      attr_accessor published_at: String

      attr_accessor updated_at: String

      attr_accessor version: String

      def initialize: (
        id: String,
        created_at: String,
        published_at: String,
        updated_at: String,
        version: String
      ) -> void

      def to_hash: -> {
        id: String,
        created_at: String,
        published_at: String,
        updated_at: String,
        version: String
      }
    end
  end
end
