module Trycourier
  module Models
    type brand_colors = { primary: String, secondary: String }

    class BrandColors < Trycourier::Internal::Type::BaseModel
      attr_reader primary: String?

      def primary=: (String) -> String

      attr_reader secondary: String?

      def secondary=: (String) -> String

      def initialize: (?primary: String, ?secondary: String) -> void

      def to_hash: -> { primary: String, secondary: String }
    end
  end
end
