module Trycourier
  module Models
    type brand_template =
      {
        enabled: bool,
        background_color: String?,
        blocks_background_color: String?,
        footer: String?,
        head: String?,
        header: String?,
        width: String?
      }

    class BrandTemplate < Trycourier::Internal::Type::BaseModel
      attr_accessor enabled: bool

      attr_accessor background_color: String?

      attr_accessor blocks_background_color: String?

      attr_accessor footer: String?

      attr_accessor head: String?

      attr_accessor header: String?

      attr_accessor width: String?

      def initialize: (
        enabled: bool,
        ?background_color: String?,
        ?blocks_background_color: String?,
        ?footer: String?,
        ?head: String?,
        ?header: String?,
        ?width: String?
      ) -> void

      def to_hash: -> {
        enabled: bool,
        background_color: String?,
        blocks_background_color: String?,
        footer: String?,
        head: String?,
        header: String?,
        width: String?
      }
    end
  end
end
