module Trycourier
  module Models
    type bulk_add_users_params =
      { users: ::Array[Trycourier::InboundBulkMessageUser] }
      & Trycourier::Internal::Type::request_parameters

    class BulkAddUsersParams < Trycourier::Internal::Type::BaseModel
      extend Trycourier::Internal::Type::RequestParameters::Converter
      include Trycourier::Internal::Type::RequestParameters

      attr_accessor users: ::Array[Trycourier::InboundBulkMessageUser]

      def initialize: (
        users: ::Array[Trycourier::InboundBulkMessageUser],
        ?request_options: Trycourier::request_opts
      ) -> void

      def to_hash: -> {
        users: ::Array[Trycourier::InboundBulkMessageUser],
        request_options: Trycourier::RequestOptions
      }
    end
  end
end
