module Trycourier
  module Models
    type elemental_text_node_with_type =
      { type: Trycourier::Models::ElementalTextNodeWithType::type_ }

    class ElementalTextNodeWithType < Trycourier::Models::ElementalBaseNode
      def `type`: -> Trycourier::Models::ElementalTextNodeWithType::type_?

      def type=: (
        Trycourier::Models::ElementalTextNodeWithType::type_ _
      ) -> Trycourier::Models::ElementalTextNodeWithType::type_

      def initialize: (
        ?type: Trycourier::Models::ElementalTextNodeWithType::type_
      ) -> void

      def to_hash: -> {
        type: Trycourier::Models::ElementalTextNodeWithType::type_
      }

      type type_ = :text

      module Type
        extend Trycourier::Internal::Type::Enum

        TEXT: :text

        def self?.values: -> ::Array[Trycourier::Models::ElementalTextNodeWithType::type_]
      end
    end
  end
end
