module Trycourier
  module Models
    type expo = Trycourier::Token | Trycourier::MultipleTokens

    module Expo
      extend Trycourier::Internal::Type::Union

      def self?.variants: -> ::Array[Trycourier::Models::expo]
    end
  end
end
