module Trycourier
  module Models
    type filter_config =
      Trycourier::SingleFilterConfig | Trycourier::NestedFilterConfig

    module FilterConfig
      extend Trycourier::Internal::Type::Union

      def self?.variants: -> ::Array[Trycourier::Models::filter_config]
    end
  end
end
