module Trycourier
  module Models
    type filter =
      Trycourier::SingleFilterConfig | Trycourier::NestedFilterConfig

    module Filter
      extend Trycourier::Internal::Type::Union

      def self?.variants: -> ::Array[Trycourier::Models::filter]
    end
  end
end
