module Trycourier
  module Models
    type filter = { filters: ::Array[Trycourier::Models::filter_config] }

    class Filter < Trycourier::Internal::Type::BaseModel
      attr_accessor filters: ::Array[Trycourier::Models::filter_config]

      def initialize: (
        filters: ::Array[Trycourier::Models::filter_config]
      ) -> void

      def to_hash: -> { filters: ::Array[Trycourier::Models::filter_config] }
    end
  end
end
