module Trycourier
  module Models
    type intercom_recipient = { id: String }

    class IntercomRecipient < Trycourier::Internal::Type::BaseModel
      attr_accessor id: String

      def initialize: (id: String) -> void

      def to_hash: -> { id: String }
    end
  end
end
