module Trycourier
  module Models
    type list_list_response =
      { items: ::Array[Trycourier::UserList], paging: Trycourier::Paging }

    class ListListResponse < Trycourier::Internal::Type::BaseModel
      attr_accessor items: ::Array[Trycourier::UserList]

      attr_accessor paging: Trycourier::Paging

      def initialize: (
        items: ::Array[Trycourier::UserList],
        paging: Trycourier::Paging
      ) -> void

      def to_hash: -> {
        items: ::Array[Trycourier::UserList],
        paging: Trycourier::Paging
      }
    end
  end
end
