module Trycourier
  module Models
    type recipient =
      {
        account_id: String?,
        context: Trycourier::MessageContext?,
        data: ::Hash[Symbol, top]?,
        email: String?,
        list_id: String?,
        locale: String?,
        phone_number: String?,
        preferences: Trycourier::ProfilePreferences?,
        tenant_id: String?,
        user_id: String?
      }

    class Recipient < Trycourier::Internal::Type::BaseModel
      attr_accessor account_id: String?

      attr_accessor context: Trycourier::MessageContext?

      attr_accessor data: ::Hash[Symbol, top]?

      attr_accessor email: String?

      attr_accessor list_id: String?

      attr_accessor locale: String?

      attr_accessor phone_number: String?

      attr_accessor preferences: Trycourier::ProfilePreferences?

      attr_accessor tenant_id: String?

      attr_accessor user_id: String?

      def initialize: (
        ?account_id: String?,
        ?context: Trycourier::MessageContext?,
        ?data: ::Hash[Symbol, top]?,
        ?email: String?,
        ?list_id: String?,
        ?locale: String?,
        ?phone_number: String?,
        ?preferences: Trycourier::ProfilePreferences?,
        ?tenant_id: String?,
        ?user_id: String?
      ) -> void

      def to_hash: -> {
        account_id: String?,
        context: Trycourier::MessageContext?,
        data: ::Hash[Symbol, top]?,
        email: String?,
        list_id: String?,
        locale: String?,
        phone_number: String?,
        preferences: Trycourier::ProfilePreferences?,
        tenant_id: String?,
        user_id: String?
      }
    end
  end
end
