module Trycourier
  module Models
    type recipient =
      {
        account_id: String?,
        context: Trycourier::MessageContext?,
        data: ::Hash[Symbol, top]?,
        email: String?,
        locale: String?,
        phone_number: String?,
        preferences: Trycourier::Recipient::Preferences?,
        tenant_id: String?,
        user_id: String?
      }

    class Recipient < Trycourier::Internal::Type::BaseModel
      attr_accessor account_id: String?

      attr_accessor context: Trycourier::MessageContext?

      attr_accessor data: ::Hash[Symbol, top]?

      attr_accessor email: String?

      attr_accessor locale: String?

      attr_accessor phone_number: String?

      attr_accessor preferences: Trycourier::Recipient::Preferences?

      attr_accessor tenant_id: String?

      attr_accessor user_id: String?

      def initialize: (
        ?account_id: String?,
        ?context: Trycourier::MessageContext?,
        ?data: ::Hash[Symbol, top]?,
        ?email: String?,
        ?locale: String?,
        ?phone_number: String?,
        ?preferences: Trycourier::Recipient::Preferences?,
        ?tenant_id: String?,
        ?user_id: String?
      ) -> void

      def to_hash: -> {
        account_id: String?,
        context: Trycourier::MessageContext?,
        data: ::Hash[Symbol, top]?,
        email: String?,
        locale: String?,
        phone_number: String?,
        preferences: Trycourier::Recipient::Preferences?,
        tenant_id: String?,
        user_id: String?
      }

      type preferences =
        {
          notifications: ::Hash[Symbol, Trycourier::Preference],
          categories: ::Hash[Symbol, Trycourier::Preference]?,
          template_id: String?
        }

      class Preferences < Trycourier::Internal::Type::BaseModel
        attr_accessor notifications: ::Hash[Symbol, Trycourier::Preference]

        attr_accessor categories: ::Hash[Symbol, Trycourier::Preference]?

        attr_accessor template_id: String?

        def initialize: (
          notifications: ::Hash[Symbol, Trycourier::Preference],
          ?categories: ::Hash[Symbol, Trycourier::Preference]?,
          ?template_id: String?
        ) -> void

        def to_hash: -> {
          notifications: ::Hash[Symbol, Trycourier::Preference],
          categories: ::Hash[Symbol, Trycourier::Preference]?,
          template_id: String?
        }
      end
    end
  end
end
