module Trycourier
  module Models
    type request_archive_params =
      {  } & Trycourier::Internal::Type::request_parameters

    class RequestArchiveParams < Trycourier::Internal::Type::BaseModel
      extend Trycourier::Internal::Type::RequestParameters::Converter
      include Trycourier::Internal::Type::RequestParameters

      def initialize: (?request_options: Trycourier::request_opts) -> void

      def to_hash: -> { request_options: Trycourier::RequestOptions }
    end
  end
end
