module Trycourier
  module Models
    type send_to_ms_teams_user_id =
      { service_url: String, tenant_id: String, user_id: String }

    class SendToMsTeamsUserID < Trycourier::Internal::Type::BaseModel
      attr_accessor service_url: String

      attr_accessor tenant_id: String

      attr_accessor user_id: String

      def initialize: (
        service_url: String,
        tenant_id: String,
        user_id: String
      ) -> void

      def to_hash: -> {
        service_url: String,
        tenant_id: String,
        user_id: String
      }
    end
  end
end
