module Trycourier
  module Models
    type send_direct_message = { user_id: String }

    class SendDirectMessage < Trycourier::Internal::Type::BaseModel
      attr_accessor user_id: String

      def initialize: (user_id: String) -> void

      def to_hash: -> { user_id: String }
    end
  end
end
