module Trycourier
  module Models
    type slack_base_properties = { access_token: String }

    class SlackBaseProperties < Trycourier::Internal::Type::BaseModel
      attr_accessor access_token: String

      def initialize: (access_token: String) -> void

      def to_hash: -> { access_token: String }
    end
  end
end
