module Trycourier
  module Models
    type token = { token: String }

    class Token < Trycourier::Internal::Type::BaseModel
      attr_accessor token: String

      def initialize: (token: String) -> void

      def to_hash: -> { token: String }
    end
  end
end
