module Trycourier
  module Models
    module Profiles
      type list_subscribe_params =
        { lists: ::Array[Trycourier::SubscribeToListsRequestItem] }
        & Trycourier::Internal::Type::request_parameters

      class ListSubscribeParams < Trycourier::Internal::Type::BaseModel
        extend Trycourier::Internal::Type::RequestParameters::Converter
        include Trycourier::Internal::Type::RequestParameters

        attr_accessor lists: ::Array[Trycourier::SubscribeToListsRequestItem]

        def initialize: (
          lists: ::Array[Trycourier::SubscribeToListsRequestItem],
          ?request_options: Trycourier::request_opts
        ) -> void

        def to_hash: -> {
          lists: ::Array[Trycourier::SubscribeToListsRequestItem],
          request_options: Trycourier::RequestOptions
        }
      end
    end
  end
end
