module Courier
  module Resources
    class Automations
      class Runs
        def list: (
          ?cursor: String,
          ?end_date: String,
          ?limit: String,
          ?start_date: String,
          ?status: String,
          ?template_id: String,
          ?request_options: Courier::request_opts
        ) -> Courier::AutomationRunListResponse

        def list_steps: (
          String id,
          ?request_options: Courier::request_opts
        ) -> Courier::AutomationRunStepsResponse

        def initialize: (client: Courier::Client) -> void
      end
    end
  end
end
