module Courier
  module Models
    type audience_retrieve_params =
      { audience_id: String } & Courier::Internal::Type::request_parameters

    class AudienceRetrieveParams < Courier::Internal::Type::BaseModel
      extend Courier::Internal::Type::RequestParameters::Converter
      include Courier::Internal::Type::RequestParameters

      attr_accessor audience_id: String

      def initialize: (
        audience_id: String,
        ?request_options: Courier::request_opts
      ) -> void

      def to_hash: -> {
        audience_id: String,
        request_options: Courier::RequestOptions
      }
    end
  end
end
