module Courier
  module Models
    type audience_recipient =
      {
        audience_id: String,
        data: ::Hash[Symbol, top]?,
        filters: ::Array[Courier::AudienceFilter]?
      }

    class AudienceRecipient < Courier::Internal::Type::BaseModel
      attr_accessor audience_id: String

      attr_accessor data: ::Hash[Symbol, top]?

      attr_accessor filters: ::Array[Courier::AudienceFilter]?

      def initialize: (
        audience_id: String,
        ?data: ::Hash[Symbol, top]?,
        ?filters: ::Array[Courier::AudienceFilter]?
      ) -> void

      def to_hash: -> {
        audience_id: String,
        data: ::Hash[Symbol, top]?,
        filters: ::Array[Courier::AudienceFilter]?
      }
    end
  end
end
