module Courier
  module Models
    type audience_update_params =
      { description: String?, filter: Courier::Models::filter?, name: String? }
      & Courier::Internal::Type::request_parameters

    class AudienceUpdateParams < Courier::Internal::Type::BaseModel
      extend Courier::Internal::Type::RequestParameters::Converter
      include Courier::Internal::Type::RequestParameters

      attr_accessor description: String?

      attr_accessor filter: Courier::Models::filter?

      attr_accessor name: String?

      def initialize: (
        ?description: String?,
        ?filter: Courier::Models::filter?,
        ?name: String?,
        ?request_options: Courier::request_opts
      ) -> void

      def to_hash: -> {
        description: String?,
        filter: Courier::Models::filter?,
        name: String?,
        request_options: Courier::RequestOptions
      }
    end
  end
end
