module Courier
  module Models
    type audience_list_members_params =
      { cursor: String? } & Courier::Internal::Type::request_parameters

    class AudienceListMembersParams < Courier::Internal::Type::BaseModel
      extend Courier::Internal::Type::RequestParameters::Converter
      include Courier::Internal::Type::RequestParameters

      attr_accessor cursor: String?

      def initialize: (
        ?cursor: String?,
        ?request_options: Courier::request_opts
      ) -> void

      def to_hash: -> {
        cursor: String?,
        request_options: Courier::RequestOptions
      }
    end
  end
end
