module Courier
  module Models
    type audit_event_list_response =
      { paging: Courier::Paging, results: ::Array[Courier::AuditEvent] }

    class AuditEventListResponse < Courier::Internal::Type::BaseModel
      attr_accessor paging: Courier::Paging

      attr_accessor results: ::Array[Courier::AuditEvent]

      def initialize: (
        paging: Courier::Paging,
        results: ::Array[Courier::AuditEvent]
      ) -> void

      def to_hash: -> {
        paging: Courier::Paging,
        results: ::Array[Courier::AuditEvent]
      }
    end
  end
end
