module Courier
  module Models
    type auth_issue_token_params =
      { expires_in: String, scope: String }
      & Courier::Internal::Type::request_parameters

    class AuthIssueTokenParams < Courier::Internal::Type::BaseModel
      extend Courier::Internal::Type::RequestParameters::Converter
      include Courier::Internal::Type::RequestParameters

      attr_accessor expires_in: String

      attr_accessor scope: String

      def initialize: (
        expires_in: String,
        scope: String,
        ?request_options: Courier::request_opts
      ) -> void

      def to_hash: -> {
        expires_in: String,
        scope: String,
        request_options: Courier::RequestOptions
      }
    end
  end
end
