module Courier
  module Models
    type brand_settings =
      { colors: Courier::BrandColors?, email: Courier::Email?, inapp: top }

    class BrandSettings < Courier::Internal::Type::BaseModel
      attr_accessor colors: Courier::BrandColors?

      attr_accessor email: Courier::Email?

      attr_reader inapp: top?

      def inapp=: (top) -> top

      def initialize: (
        ?colors: Courier::BrandColors?,
        ?email: Courier::Email?,
        ?inapp: top
      ) -> void

      def to_hash: -> {
        colors: Courier::BrandColors?,
        email: Courier::Email?,
        inapp: top
      }
    end
  end
end
