module Courier
  module Models
    type brand_settings =
      {
        colors: Courier::BrandColors?,
        email: Courier::BrandSettingsEmail?,
        inapp: Courier::BrandSettingsInApp?
      }

    class BrandSettings < Courier::Internal::Type::BaseModel
      attr_accessor colors: Courier::BrandColors?

      attr_accessor email: Courier::BrandSettingsEmail?

      attr_accessor inapp: Courier::BrandSettingsInApp?

      def initialize: (
        ?colors: Courier::BrandColors?,
        ?email: Courier::BrandSettingsEmail?,
        ?inapp: Courier::BrandSettingsInApp?
      ) -> void

      def to_hash: -> {
        colors: Courier::BrandColors?,
        email: Courier::BrandSettingsEmail?,
        inapp: Courier::BrandSettingsInApp?
      }
    end
  end
end
