module Courier
  module Models
    type brand_settings_email =
      {
        footer: Courier::EmailFooter?,
        head: Courier::EmailHead?,
        header: Courier::EmailHeader?,
        template_override: Courier::BrandSettingsEmail::TemplateOverride?
      }

    class BrandSettingsEmail < Courier::Internal::Type::BaseModel
      attr_accessor footer: Courier::EmailFooter?

      attr_accessor head: Courier::EmailHead?

      attr_accessor header: Courier::EmailHeader?

      attr_accessor template_override: Courier::BrandSettingsEmail::TemplateOverride?

      def initialize: (
        ?footer: Courier::EmailFooter?,
        ?head: Courier::EmailHead?,
        ?header: Courier::EmailHeader?,
        ?template_override: Courier::BrandSettingsEmail::TemplateOverride?
      ) -> void

      def to_hash: -> {
        footer: Courier::EmailFooter?,
        head: Courier::EmailHead?,
        header: Courier::EmailHeader?,
        template_override: Courier::BrandSettingsEmail::TemplateOverride?
      }

      type template_override =
        {
          mjml: Courier::BrandTemplate,
          footer_background_color: String?,
          footer_full_width: bool?
        }

      class TemplateOverride < Courier::Models::BrandTemplate
        def mjml: -> Courier::BrandTemplate

        def mjml=: (Courier::BrandTemplate _) -> Courier::BrandTemplate

        def footer_background_color: -> String?

        def footer_background_color=: (String? _) -> String?

        def footer_full_width: -> bool?

        def footer_full_width=: (bool? _) -> bool?

        def initialize: (
          mjml: Courier::BrandTemplate,
          ?footer_background_color: String?,
          ?footer_full_width: bool?
        ) -> void

        def to_hash: -> {
          mjml: Courier::BrandTemplate,
          footer_background_color: String?,
          footer_full_width: bool?
        }
      end
    end
  end
end
