module Courier
  module Models
    type brand_update_params =
      {
        name: String,
        settings: Courier::BrandSettings?,
        snippets: Courier::BrandSnippets?
      }
      & Courier::Internal::Type::request_parameters

    class BrandUpdateParams < Courier::Internal::Type::BaseModel
      extend Courier::Internal::Type::RequestParameters::Converter
      include Courier::Internal::Type::RequestParameters

      attr_accessor name: String

      attr_accessor settings: Courier::BrandSettings?

      attr_accessor snippets: Courier::BrandSnippets?

      def initialize: (
        name: String,
        ?settings: Courier::BrandSettings?,
        ?snippets: Courier::BrandSnippets?,
        ?request_options: Courier::request_opts
      ) -> void

      def to_hash: -> {
        name: String,
        settings: Courier::BrandSettings?,
        snippets: Courier::BrandSnippets?,
        request_options: Courier::RequestOptions
      }
    end
  end
end
