module Courier
  module Models
    type brand_snippets = { items: ::Array[Courier::BrandSnippet] }

    class BrandSnippets < Courier::Internal::Type::BaseModel
      attr_accessor items: ::Array[Courier::BrandSnippet]

      def initialize: (items: ::Array[Courier::BrandSnippet]) -> void

      def to_hash: -> { items: ::Array[Courier::BrandSnippet] }
    end
  end
end
