module Courier
  module Models
    type brand_settings_in_app =
      {
        colors: Courier::BrandColors,
        icons: Courier::Icons,
        widget_background: Courier::WidgetBackground,
        border_radius: String?,
        disable_message_icon: bool?,
        font_family: String?,
        placement: Courier::Models::BrandSettingsInApp::placement?
      }

    class BrandSettingsInApp < Courier::Internal::Type::BaseModel
      attr_accessor colors: Courier::BrandColors

      attr_accessor icons: Courier::Icons

      attr_accessor widget_background: Courier::WidgetBackground

      attr_accessor border_radius: String?

      attr_accessor disable_message_icon: bool?

      attr_accessor font_family: String?

      attr_accessor placement: Courier::Models::BrandSettingsInApp::placement?

      def initialize: (
        colors: Courier::BrandColors,
        icons: Courier::Icons,
        widget_background: Courier::WidgetBackground,
        ?border_radius: String?,
        ?disable_message_icon: bool?,
        ?font_family: String?,
        ?placement: Courier::Models::BrandSettingsInApp::placement?
      ) -> void

      def to_hash: -> {
        colors: Courier::BrandColors,
        icons: Courier::Icons,
        widget_background: Courier::WidgetBackground,
        border_radius: String?,
        disable_message_icon: bool?,
        font_family: String?,
        placement: Courier::Models::BrandSettingsInApp::placement?
      }

      type placement = :top | :bottom | :left | :right

      module Placement
        extend Courier::Internal::Type::Enum

        TOP: :top
        BOTTOM: :bottom
        LEFT: :left
        RIGHT: :right

        def self?.values: -> ::Array[Courier::Models::BrandSettingsInApp::placement]
      end
    end
  end
end
