module Courier
  module Models
    type bulk_add_users_params =
      { users: ::Array[Courier::InboundBulkMessageUser] }
      & Courier::Internal::Type::request_parameters

    class BulkAddUsersParams < Courier::Internal::Type::BaseModel
      extend Courier::Internal::Type::RequestParameters::Converter
      include Courier::Internal::Type::RequestParameters

      attr_accessor users: ::Array[Courier::InboundBulkMessageUser]

      def initialize: (
        users: ::Array[Courier::InboundBulkMessageUser],
        ?request_options: Courier::request_opts
      ) -> void

      def to_hash: -> {
        users: ::Array[Courier::InboundBulkMessageUser],
        request_options: Courier::RequestOptions
      }
    end
  end
end
