module Courier
  module Models
    type channel_preference =
      { channel: Courier::Models::channel_classification }

    class ChannelPreference < Courier::Internal::Type::BaseModel
      attr_accessor channel: Courier::Models::channel_classification

      def initialize: (channel: Courier::Models::channel_classification) -> void

      def to_hash: -> { channel: Courier::Models::channel_classification }
    end
  end
end
