module Courier
  module Models
    type content =
      Courier::Content::ElementalContentSugar
      | Courier::Tenants::ElementalContent

    module Content
      extend Courier::Internal::Type::Union

      type elemental_content_sugar = { body: String, title: String }

      class ElementalContentSugar < Courier::Internal::Type::BaseModel
        attr_accessor body: String

        attr_accessor title: String

        def initialize: (body: String, title: String) -> void

        def to_hash: -> { body: String, title: String }
      end

      def self?.variants: -> ::Array[Courier::Models::content]
    end
  end
end
