module Courier
  module Models
    type elemental_channel_node = { channel: String, raw: ::Hash[Symbol, top]? }

    class ElementalChannelNode < Courier::Models::ElementalBaseNode
      def channel: -> String

      def channel=: (String _) -> String

      def raw: -> ::Hash[Symbol, top]?

      def raw=: (::Hash[Symbol, top]? _) -> ::Hash[Symbol, top]?

      def initialize: (channel: String, ?raw: ::Hash[Symbol, top]?) -> void

      def to_hash: -> { channel: String, raw: ::Hash[Symbol, top]? }
    end
  end
end
