module Courier
  module Models
    type elemental_content =
      { elements: ::Array[Courier::Models::elemental_node], version: String }

    class ElementalContent < Courier::Internal::Type::BaseModel
      attr_accessor elements: ::Array[Courier::Models::elemental_node]

      attr_accessor version: String

      def initialize: (
        elements: ::Array[Courier::Models::elemental_node],
        version: String
      ) -> void

      def to_hash: -> {
        elements: ::Array[Courier::Models::elemental_node],
        version: String
      }
    end
  end
end
