module Courier
  module Models
    type elemental_content_sugar = { body: String, title: String }

    class ElementalContentSugar < Courier::Internal::Type::BaseModel
      attr_accessor body: String

      attr_accessor title: String

      def initialize: (body: String, title: String) -> void

      def to_hash: -> { body: String, title: String }
    end
  end
end
