module Courier
  module Models
    type email_head = { inherit_default: bool, content: String? }

    class EmailHead < Courier::Internal::Type::BaseModel
      attr_accessor inherit_default: bool

      attr_accessor content: String?

      def initialize: (inherit_default: bool, ?content: String?) -> void

      def to_hash: -> { inherit_default: bool, content: String? }
    end
  end
end
