module Courier
  module Models
    type inbound_track_event_response = { message_id: String }

    class InboundTrackEventResponse < Courier::Internal::Type::BaseModel
      attr_accessor message_id: String

      def initialize: (message_id: String) -> void

      def to_hash: -> { message_id: String }
    end
  end
end
