module Courier
  module Models
    type inbound_bulk_message_user =
      {
        data: top,
        preferences: Courier::Lists::RecipientPreferences?,
        profile: top,
        recipient: String?,
        to: Courier::UserRecipient?
      }

    class InboundBulkMessageUser < Courier::Internal::Type::BaseModel
      attr_reader data: top?

      def data=: (top) -> top

      attr_accessor preferences: Courier::Lists::RecipientPreferences?

      attr_reader profile: top?

      def profile=: (top) -> top

      attr_accessor recipient: String?

      attr_accessor to: Courier::UserRecipient?

      def initialize: (
        ?data: top,
        ?preferences: Courier::Lists::RecipientPreferences?,
        ?profile: top,
        ?recipient: String?,
        ?to: Courier::UserRecipient?
      ) -> void

      def to_hash: -> {
        data: top,
        preferences: Courier::Lists::RecipientPreferences?,
        profile: top,
        recipient: String?,
        to: Courier::UserRecipient?
      }
    end
  end
end
