module Courier
  module Models
    type journey_archive_params =
      { template_id: String } & Courier::Internal::Type::request_parameters

    class JourneyArchiveParams < Courier::Internal::Type::BaseModel
      extend Courier::Internal::Type::RequestParameters::Converter
      include Courier::Internal::Type::RequestParameters

      attr_accessor template_id: String

      def initialize: (
        template_id: String,
        ?request_options: Courier::request_opts
      ) -> void

      def to_hash: -> {
        template_id: String,
        request_options: Courier::RequestOptions
      }
    end
  end
end
