module Courier
  module Models
    type list_list_response =
      { items: ::Array[Courier::List], paging: Courier::Paging }

    class ListListResponse < Courier::Internal::Type::BaseModel
      attr_accessor items: ::Array[Courier::List]

      attr_accessor paging: Courier::Paging

      def initialize: (
        items: ::Array[Courier::List],
        paging: Courier::Paging
      ) -> void

      def to_hash: -> { items: ::Array[Courier::List], paging: Courier::Paging }
    end
  end
end
