module Courier
  module Models
    type list_update_params =
      { name: String, preferences: Courier::RecipientPreferences? }
      & Courier::Internal::Type::request_parameters

    class ListUpdateParams < Courier::Internal::Type::BaseModel
      extend Courier::Internal::Type::RequestParameters::Converter
      include Courier::Internal::Type::RequestParameters

      attr_accessor name: String

      attr_accessor preferences: Courier::RecipientPreferences?

      def initialize: (
        name: String,
        ?preferences: Courier::RecipientPreferences?,
        ?request_options: Courier::request_opts
      ) -> void

      def to_hash: -> {
        name: String,
        preferences: Courier::RecipientPreferences?,
        request_options: Courier::RequestOptions
      }
    end
  end
end
