module Courier
  module Models
    type list_filter =
      {
        operator: Courier::Models::ListFilter::operator,
        path: Courier::Models::ListFilter::path,
        value: String
      }

    class ListFilter < Courier::Internal::Type::BaseModel
      attr_accessor operator: Courier::Models::ListFilter::operator

      attr_accessor path: Courier::Models::ListFilter::path

      attr_accessor value: String

      def initialize: (
        operator: Courier::Models::ListFilter::operator,
        path: Courier::Models::ListFilter::path,
        value: String
      ) -> void

      def to_hash: -> {
        operator: Courier::Models::ListFilter::operator,
        path: Courier::Models::ListFilter::path,
        value: String
      }

      type operator = :MEMBER_OF

      module Operator
        extend Courier::Internal::Type::Enum

        MEMBER_OF: :MEMBER_OF

        def self?.values: -> ::Array[Courier::Models::ListFilter::operator]
      end

      type path = :account_id

      module Path
        extend Courier::Internal::Type::Enum

        ACCOUNT_ID: :account_id

        def self?.values: -> ::Array[Courier::Models::ListFilter::path]
      end
    end
  end
end
