module Courier
  module Models
    type message_get_content_params =
      {  } & Courier::Internal::Type::request_parameters

    class MessageGetContentParams < Courier::Internal::Type::BaseModel
      extend Courier::Internal::Type::RequestParameters::Converter
      include Courier::Internal::Type::RequestParameters

      def initialize: (?request_options: Courier::request_opts) -> void

      def to_hash: -> { request_options: Courier::RequestOptions }
    end
  end
end
