module Courier
  module Models
    type message_list_response =
      { paging: Courier::Paging, results: ::Array[Courier::MessageDetails] }

    class MessageListResponse < Courier::Internal::Type::BaseModel
      attr_accessor paging: Courier::Paging

      attr_accessor results: ::Array[Courier::MessageDetails]

      def initialize: (
        paging: Courier::Paging,
        results: ::Array[Courier::MessageDetails]
      ) -> void

      def to_hash: -> {
        paging: Courier::Paging,
        results: ::Array[Courier::MessageDetails]
      }
    end
  end
end
