module Courier
  module Models
    type message =
      Courier::Message::ContentMessage | Courier::Message::TemplateMessage

    module Message
      extend Courier::Internal::Type::Union

      def self?.variants: -> ::Array[Courier::Models::message]
    end
  end
end
