module Courier
  module Models
    type message_resend_response = { message_id: String }

    class MessageResendResponse < Courier::Internal::Type::BaseModel
      attr_accessor message_id: String

      def initialize: (message_id: String) -> void

      def to_hash: -> { message_id: String }
    end
  end
end
