module Courier
  module Models
    type message_history_params =
      { type: String? } & Courier::Internal::Type::request_parameters

    class MessageHistoryParams < Courier::Internal::Type::BaseModel
      extend Courier::Internal::Type::RequestParameters::Converter
      include Courier::Internal::Type::RequestParameters

      attr_accessor type: String?

      def initialize: (
        ?type: String?,
        ?request_options: Courier::request_opts
      ) -> void

      def to_hash: -> {
        type: String?,
        request_options: Courier::RequestOptions
      }
    end
  end
end
