module Courier
  module Models
    type metadata = { utm: Courier::Utm? }

    class Metadata < Courier::Internal::Type::BaseModel
      attr_accessor utm: Courier::Utm?

      def initialize: (?utm: Courier::Utm?) -> void

      def to_hash: -> { utm: Courier::Utm? }
    end
  end
end
