module Courier
  module Models
    type multiple_tokens = { tokens: ::Array[Courier::Token] }

    class MultipleTokens < Courier::Internal::Type::BaseModel
      attr_accessor tokens: ::Array[Courier::Token]

      def initialize: (tokens: ::Array[Courier::Token]) -> void

      def to_hash: -> { tokens: ::Array[Courier::Token] }
    end
  end
end
