module Courier
  module Models
    type notification_put_locale_params =
      { id: String, locale_id: String }
      & Courier::Internal::Type::request_parameters

    class NotificationPutLocaleParams < Courier::Models::NotificationLocalePutRequest
      extend Courier::Internal::Type::RequestParameters::Converter
      include Courier::Internal::Type::RequestParameters

      def id: -> String

      def id=: (String _) -> String

      def locale_id: -> String

      def locale_id=: (String _) -> String

      def initialize: (
        id: String,
        locale_id: String,
        ?request_options: Courier::request_opts
      ) -> void

      def to_hash: -> {
        id: String,
        locale_id: String,
        request_options: Courier::RequestOptions
      }
    end
  end
end
