module Courier
  module Models
    type notification_template_alias = String | ::Array[String]

    module NotificationTemplateAlias
      extend Courier::Internal::Type::Union

      def self?.variants: -> ::Array[Courier::Models::notification_template_alias]

      StringArray: Courier::Internal::Type::Converter
    end
  end
end
