module Courier
  module Models
    type notification_template_response =
      {
        created: Integer,
        creator: String,
        notification: Courier::NotificationTemplateResponse::Notification,
        state: Courier::Models::NotificationTemplateResponse::state,
        updated: Integer,
        updater: String
      }

    class NotificationTemplateResponse < Courier::Internal::Type::BaseModel
      attr_accessor created: Integer

      attr_accessor creator: String

      attr_accessor notification: Courier::NotificationTemplateResponse::Notification

      attr_accessor state: Courier::Models::NotificationTemplateResponse::state

      attr_reader updated: Integer?

      def updated=: (Integer) -> Integer

      attr_reader updater: String?

      def updater=: (String) -> String

      def initialize: (
        created: Integer,
        creator: String,
        notification: Courier::NotificationTemplateResponse::Notification,
        state: Courier::Models::NotificationTemplateResponse::state,
        ?updated: Integer,
        ?updater: String
      ) -> void

      def to_hash: -> {
        created: Integer,
        creator: String,
        notification: Courier::NotificationTemplateResponse::Notification,
        state: Courier::Models::NotificationTemplateResponse::state,
        updated: Integer,
        updater: String
      }

      type notification = { id: String }

      class Notification < Courier::Models::NotificationTemplatePayload
        def id: -> String

        def id=: (String _) -> String

        def initialize: (id: String) -> void

        def to_hash: -> { id: String }
      end

      type state = :DRAFT | :PUBLISHED

      module State
        extend Courier::Internal::Type::Enum

        DRAFT: :DRAFT
        PUBLISHED: :PUBLISHED

        def self?.values: -> ::Array[Courier::Models::NotificationTemplateResponse::state]
      end
    end
  end
end
