module Courier
  module Models
    type notification_list_response =
      {
        paging: Courier::Paging,
        results: ::Array[Courier::Models::NotificationListResponse::result]
      }

    class NotificationListResponse < Courier::Internal::Type::BaseModel
      attr_accessor paging: Courier::Paging

      attr_accessor results: ::Array[Courier::Models::NotificationListResponse::result]

      def initialize: (
        paging: Courier::Paging,
        results: ::Array[Courier::Models::NotificationListResponse::result]
      ) -> void

      def to_hash: -> {
        paging: Courier::Paging,
        results: ::Array[Courier::Models::NotificationListResponse::result]
      }

      type result =
        Courier::Models::NotificationListResponse::Result::Notification
        | Courier::NotificationTemplateSummary

      module Result
        extend Courier::Internal::Type::Union

        type notification =
          {
            id: String,
            created_at: Integer,
            event_ids: ::Array[String],
            routing: Courier::MessageRouting,
            topic_id: String,
            updated_at: Integer,
            note: String,
            tags: Courier::Models::NotificationListResponse::Result::Notification::Tags?,
            title: String?
          }

        class Notification < Courier::Internal::Type::BaseModel
          attr_accessor id: String

          attr_accessor created_at: Integer

          attr_accessor event_ids: ::Array[String]

          attr_accessor routing: Courier::MessageRouting

          attr_accessor topic_id: String

          attr_accessor updated_at: Integer

          attr_reader note: String?

          def note=: (String) -> String

          attr_accessor tags: Courier::Models::NotificationListResponse::Result::Notification::Tags?

          attr_accessor title: String?

          def initialize: (
            id: String,
            created_at: Integer,
            event_ids: ::Array[String],
            routing: Courier::MessageRouting,
            topic_id: String,
            updated_at: Integer,
            ?note: String,
            ?tags: Courier::Models::NotificationListResponse::Result::Notification::Tags?,
            ?title: String?
          ) -> void

          def to_hash: -> {
            id: String,
            created_at: Integer,
            event_ids: ::Array[String],
            routing: Courier::MessageRouting,
            topic_id: String,
            updated_at: Integer,
            note: String,
            tags: Courier::Models::NotificationListResponse::Result::Notification::Tags?,
            title: String?
          }

          type tags =
            {
              data: ::Array[Courier::Models::NotificationListResponse::Result::Notification::Tags::Data]
            }

          class Tags < Courier::Internal::Type::BaseModel
            attr_accessor data: ::Array[Courier::Models::NotificationListResponse::Result::Notification::Tags::Data]

            def initialize: (
              data: ::Array[Courier::Models::NotificationListResponse::Result::Notification::Tags::Data]
            ) -> void

            def to_hash: -> {
              data: ::Array[Courier::Models::NotificationListResponse::Result::Notification::Tags::Data]
            }

            type data = { id: String, name: String }

            class Data < Courier::Internal::Type::BaseModel
              attr_accessor id: String

              attr_accessor name: String

              def initialize: (id: String, name: String) -> void

              def to_hash: -> { id: String, name: String }
            end
          end
        end

        def self?.variants: -> ::Array[Courier::Models::NotificationListResponse::result]
      end
    end
  end
end
