module Courier
  module Models
    type pagerduty_recipient = { pagerduty: Courier::Pagerduty }

    class PagerdutyRecipient < Courier::Internal::Type::BaseModel
      attr_accessor pagerduty: Courier::Pagerduty

      def initialize: (pagerduty: Courier::Pagerduty) -> void

      def to_hash: -> { pagerduty: Courier::Pagerduty }
    end
  end
end
