module Courier
  module Models
    type preference_topic_list_response =
      { results: ::Array[Courier::PreferenceTopicGetResponse] }

    class PreferenceTopicListResponse < Courier::Internal::Type::BaseModel
      attr_accessor results: ::Array[Courier::PreferenceTopicGetResponse]

      def initialize: (
        results: ::Array[Courier::PreferenceTopicGetResponse]
      ) -> void

      def to_hash: -> { results: ::Array[Courier::PreferenceTopicGetResponse] }
    end
  end
end
