module Courier
  module Models
    type preference_section_list_response =
      { results: ::Array[Courier::PreferenceSectionGetResponse] }

    class PreferenceSectionListResponse < Courier::Internal::Type::BaseModel
      attr_accessor results: ::Array[Courier::PreferenceSectionGetResponse]

      def initialize: (
        results: ::Array[Courier::PreferenceSectionGetResponse]
      ) -> void

      def to_hash: -> {
        results: ::Array[Courier::PreferenceSectionGetResponse]
      }
    end
  end
end
