module Courier
  module Models
    type preview_archive_device_set_params =
      { device_set_id: String } & Courier::Internal::Type::request_parameters

    class PreviewArchiveDeviceSetParams < Courier::Internal::Type::BaseModel
      extend Courier::Internal::Type::RequestParameters::Converter
      include Courier::Internal::Type::RequestParameters

      attr_accessor device_set_id: String

      def initialize: (
        device_set_id: String,
        ?request_options: Courier::request_opts
      ) -> void

      def to_hash: -> {
        device_set_id: String,
        request_options: Courier::RequestOptions
      }
    end
  end
end
