module Courier
  module Models
    type preview_create_device_set_params =
      {  } & Courier::Internal::Type::request_parameters

    class PreviewCreateDeviceSetParams < Courier::Models::CreateDeviceSetRequest
      extend Courier::Internal::Type::RequestParameters::Converter
      include Courier::Internal::Type::RequestParameters

      def initialize: (?request_options: Courier::request_opts) -> void

      def to_hash: -> { request_options: Courier::RequestOptions }
    end
  end
end
