module Courier
  module Models
    type profile_replace_response =
      { status: Courier::Models::ProfileReplaceResponse::status }

    class ProfileReplaceResponse < Courier::Internal::Type::BaseModel
      attr_accessor status: Courier::Models::ProfileReplaceResponse::status

      def initialize: (
        status: Courier::Models::ProfileReplaceResponse::status
      ) -> void

      def to_hash: -> {
        status: Courier::Models::ProfileReplaceResponse::status
      }

      type status = :SUCCESS

      module Status
        extend Courier::Internal::Type::Enum

        SUCCESS: :SUCCESS

        def self?.values: -> ::Array[Courier::Models::ProfileReplaceResponse::status]
      end
    end
  end
end
