module Courier
  module Models
    type profile_create_params =
      { profile: ::Hash[Symbol, top] }
      & Courier::Internal::Type::request_parameters

    class ProfileCreateParams < Courier::Internal::Type::BaseModel
      extend Courier::Internal::Type::RequestParameters::Converter
      include Courier::Internal::Type::RequestParameters

      attr_accessor profile: ::Hash[Symbol, top]

      def initialize: (
        profile: ::Hash[Symbol, top],
        ?request_options: Courier::request_opts
      ) -> void

      def to_hash: -> {
        profile: ::Hash[Symbol, top],
        request_options: Courier::RequestOptions
      }
    end
  end
end
