module Courier
  module Models
    type profile_retrieve_response =
      {
        profile: ::Hash[Symbol, top],
        preferences: Courier::RecipientPreferences?
      }

    class ProfileRetrieveResponse < Courier::Internal::Type::BaseModel
      attr_accessor profile: ::Hash[Symbol, top]

      attr_accessor preferences: Courier::RecipientPreferences?

      def initialize: (
        profile: ::Hash[Symbol, top],
        ?preferences: Courier::RecipientPreferences?
      ) -> void

      def to_hash: -> {
        profile: ::Hash[Symbol, top],
        preferences: Courier::RecipientPreferences?
      }
    end
  end
end
