module Courier
  module Models
    type profile_create_response =
      { status: Courier::Models::ProfileCreateResponse::status }

    class ProfileCreateResponse < Courier::Internal::Type::BaseModel
      attr_accessor status: Courier::Models::ProfileCreateResponse::status

      def initialize: (
        status: Courier::Models::ProfileCreateResponse::status
      ) -> void

      def to_hash: -> { status: Courier::Models::ProfileCreateResponse::status }

      type status = :SUCCESS

      module Status
        extend Courier::Internal::Type::Enum

        SUCCESS: :SUCCESS

        def self?.values: -> ::Array[Courier::Models::ProfileCreateResponse::status]
      end
    end
  end
end
