module Courier
  module Models
    type recipient =
      {
        account_id: String?,
        context: Courier::MessageContext?,
        data: ::Hash[Symbol, top]?,
        email: String?,
        locale: String?,
        phone_number: String?,
        preferences: Courier::Recipient::Preferences?,
        tenant_id: String?,
        user_id: String?
      }

    class Recipient < Courier::Internal::Type::BaseModel
      attr_accessor account_id: String?

      attr_accessor context: Courier::MessageContext?

      attr_accessor data: ::Hash[Symbol, top]?

      attr_accessor email: String?

      attr_accessor locale: String?

      attr_accessor phone_number: String?

      attr_accessor preferences: Courier::Recipient::Preferences?

      attr_accessor tenant_id: String?

      attr_accessor user_id: String?

      def initialize: (
        ?account_id: String?,
        ?context: Courier::MessageContext?,
        ?data: ::Hash[Symbol, top]?,
        ?email: String?,
        ?locale: String?,
        ?phone_number: String?,
        ?preferences: Courier::Recipient::Preferences?,
        ?tenant_id: String?,
        ?user_id: String?
      ) -> void

      def to_hash: -> {
        account_id: String?,
        context: Courier::MessageContext?,
        data: ::Hash[Symbol, top]?,
        email: String?,
        locale: String?,
        phone_number: String?,
        preferences: Courier::Recipient::Preferences?,
        tenant_id: String?,
        user_id: String?
      }

      type preferences =
        {
          notifications: ::Hash[Symbol, Courier::Recipient::Preferences::Notification],
          categories: ::Hash[Symbol, Courier::Recipient::Preferences::Category]?,
          template_id: String?
        }

      class Preferences < Courier::Internal::Type::BaseModel
        attr_accessor notifications: ::Hash[Symbol, Courier::Recipient::Preferences::Notification]

        attr_accessor categories: ::Hash[Symbol, Courier::Recipient::Preferences::Category]?

        attr_accessor template_id: String?

        def initialize: (
          notifications: ::Hash[Symbol, Courier::Recipient::Preferences::Notification],
          ?categories: ::Hash[Symbol, Courier::Recipient::Preferences::Category]?,
          ?template_id: String?
        ) -> void

        def to_hash: -> {
          notifications: ::Hash[Symbol, Courier::Recipient::Preferences::Notification],
          categories: ::Hash[Symbol, Courier::Recipient::Preferences::Category]?,
          template_id: String?
        }

        type notification =
          {
            status: Courier::Models::Users::preference_status,
            channel_preferences: ::Array[Courier::Recipient::Preferences::Notification::ChannelPreference]?,
            rules: ::Array[Courier::Recipient::Preferences::Notification::Rule]?,
            source: Courier::Models::Recipient::Preferences::Notification::source?
          }

        class Notification < Courier::Internal::Type::BaseModel
          attr_accessor status: Courier::Models::Users::preference_status

          attr_accessor channel_preferences: ::Array[Courier::Recipient::Preferences::Notification::ChannelPreference]?

          attr_accessor rules: ::Array[Courier::Recipient::Preferences::Notification::Rule]?

          attr_accessor source: Courier::Models::Recipient::Preferences::Notification::source?

          def initialize: (
            status: Courier::Models::Users::preference_status,
            ?channel_preferences: ::Array[Courier::Recipient::Preferences::Notification::ChannelPreference]?,
            ?rules: ::Array[Courier::Recipient::Preferences::Notification::Rule]?,
            ?source: Courier::Models::Recipient::Preferences::Notification::source?
          ) -> void

          def to_hash: -> {
            status: Courier::Models::Users::preference_status,
            channel_preferences: ::Array[Courier::Recipient::Preferences::Notification::ChannelPreference]?,
            rules: ::Array[Courier::Recipient::Preferences::Notification::Rule]?,
            source: Courier::Models::Recipient::Preferences::Notification::source?
          }

          type channel_preference =
            {
              channel: Courier::Models::Tenants::DefaultPreferences::channel_classification
            }

          class ChannelPreference < Courier::Internal::Type::BaseModel
            attr_accessor channel: Courier::Models::Tenants::DefaultPreferences::channel_classification

            def initialize: (
              channel: Courier::Models::Tenants::DefaultPreferences::channel_classification
            ) -> void

            def to_hash: -> {
              channel: Courier::Models::Tenants::DefaultPreferences::channel_classification
            }
          end

          type rule = { until_: String, start: String? }

          class Rule < Courier::Internal::Type::BaseModel
            attr_accessor until_: String

            attr_accessor start: String?

            def initialize: (until_: String, ?start: String?) -> void

            def to_hash: -> { until_: String, start: String? }
          end

          type source = :subscription | :list | :recipient

          module Source
            extend Courier::Internal::Type::Enum

            SUBSCRIPTION: :subscription
            LIST: :list
            RECIPIENT: :recipient

            def self?.values: -> ::Array[Courier::Models::Recipient::Preferences::Notification::source]
          end
        end

        type category =
          {
            status: Courier::Models::Users::preference_status,
            channel_preferences: ::Array[Courier::Recipient::Preferences::Category::ChannelPreference]?,
            rules: ::Array[Courier::Recipient::Preferences::Category::Rule]?,
            source: Courier::Models::Recipient::Preferences::Category::source?
          }

        class Category < Courier::Internal::Type::BaseModel
          attr_accessor status: Courier::Models::Users::preference_status

          attr_accessor channel_preferences: ::Array[Courier::Recipient::Preferences::Category::ChannelPreference]?

          attr_accessor rules: ::Array[Courier::Recipient::Preferences::Category::Rule]?

          attr_accessor source: Courier::Models::Recipient::Preferences::Category::source?

          def initialize: (
            status: Courier::Models::Users::preference_status,
            ?channel_preferences: ::Array[Courier::Recipient::Preferences::Category::ChannelPreference]?,
            ?rules: ::Array[Courier::Recipient::Preferences::Category::Rule]?,
            ?source: Courier::Models::Recipient::Preferences::Category::source?
          ) -> void

          def to_hash: -> {
            status: Courier::Models::Users::preference_status,
            channel_preferences: ::Array[Courier::Recipient::Preferences::Category::ChannelPreference]?,
            rules: ::Array[Courier::Recipient::Preferences::Category::Rule]?,
            source: Courier::Models::Recipient::Preferences::Category::source?
          }

          type channel_preference =
            {
              channel: Courier::Models::Tenants::DefaultPreferences::channel_classification
            }

          class ChannelPreference < Courier::Internal::Type::BaseModel
            attr_accessor channel: Courier::Models::Tenants::DefaultPreferences::channel_classification

            def initialize: (
              channel: Courier::Models::Tenants::DefaultPreferences::channel_classification
            ) -> void

            def to_hash: -> {
              channel: Courier::Models::Tenants::DefaultPreferences::channel_classification
            }
          end

          type rule = { until_: String, start: String? }

          class Rule < Courier::Internal::Type::BaseModel
            attr_accessor until_: String

            attr_accessor start: String?

            def initialize: (until_: String, ?start: String?) -> void

            def to_hash: -> { until_: String, start: String? }
          end

          type source = :subscription | :list | :recipient

          module Source
            extend Courier::Internal::Type::Enum

            SUBSCRIPTION: :subscription
            LIST: :list
            RECIPIENT: :recipient

            def self?.values: -> ::Array[Courier::Models::Recipient::Preferences::Category::source]
          end
        end
      end
    end
  end
end
