module Courier
  module Models
    type routing_method = :all | :single

    module RoutingMethod
      extend Courier::Internal::Type::Enum

      ALL: :all
      SINGLE: :single

      def self?.values: -> ::Array[Courier::Models::routing_method]
    end
  end
end
