module Courier
  module Models
    type routing_strategy_summary =
      {
        id: String,
        created: Integer,
        creator: String,
        name: String,
        description: String?,
        tags: ::Array[String]?,
        updated: Integer?,
        updater: String?
      }

    class RoutingStrategySummary < Courier::Internal::Type::BaseModel
      attr_accessor id: String

      attr_accessor created: Integer

      attr_accessor creator: String

      attr_accessor name: String

      attr_accessor description: String?

      attr_accessor tags: ::Array[String]?

      attr_accessor updated: Integer?

      attr_accessor updater: String?

      def initialize: (
        id: String,
        created: Integer,
        creator: String,
        name: String,
        ?description: String?,
        ?tags: ::Array[String]?,
        ?updated: Integer?,
        ?updater: String?
      ) -> void

      def to_hash: -> {
        id: String,
        created: Integer,
        creator: String,
        name: String,
        description: String?,
        tags: ::Array[String]?,
        updated: Integer?,
        updater: String?
      }
    end
  end
end
