module Courier
  module Models
    type send_to_ms_teams_user_id =
      { user_id: String, service_url: String, tenant_id: String }

    class SendToMsTeamsUserID < Courier::Internal::Type::BaseModel
      attr_accessor user_id: String

      attr_reader service_url: String?

      def service_url=: (String) -> String

      attr_reader tenant_id: String?

      def tenant_id=: (String) -> String

      def initialize: (
        user_id: String,
        ?service_url: String,
        ?tenant_id: String
      ) -> void

      def to_hash: -> {
        user_id: String,
        service_url: String,
        tenant_id: String
      }
    end
  end
end
