module Courier
  module Models
    type send_send_message_params =
      { message: Courier::Models::message }
      & Courier::Internal::Type::request_parameters

    class SendSendMessageParams < Courier::Internal::Type::BaseModel
      extend Courier::Internal::Type::RequestParameters::Converter
      include Courier::Internal::Type::RequestParameters

      attr_accessor message: Courier::Models::message

      def initialize: (
        message: Courier::Models::message,
        ?request_options: Courier::request_opts
      ) -> void

      def to_hash: -> {
        message: Courier::Models::message,
        request_options: Courier::RequestOptions
      }
    end
  end
end
