module Courier
  module Models
    type send_message_params =
      { message: Courier::SendMessageParams::Message }
      & Courier::Internal::Type::request_parameters

    class SendMessageParams < Courier::Internal::Type::BaseModel
      extend Courier::Internal::Type::RequestParameters::Converter
      include Courier::Internal::Type::RequestParameters

      attr_accessor message: Courier::SendMessageParams::Message

      def initialize: (
        message: Courier::SendMessageParams::Message,
        ?request_options: Courier::request_opts
      ) -> void

      def to_hash: -> {
        message: Courier::SendMessageParams::Message,
        request_options: Courier::RequestOptions
      }

      type message =
        {
          brand_id: String?,
          channels: ::Hash[Symbol, Courier::SendMessageParams::Message::Channel]?,
          content: Courier::Models::SendMessageParams::Message::content,
          context: Courier::MessageContext?,
          data: ::Hash[Symbol, top]?,
          delay: Courier::SendMessageParams::Message::Delay?,
          expiry: Courier::SendMessageParams::Message::Expiry?,
          metadata: Courier::SendMessageParams::Message::Metadata?,
          preferences: Courier::SendMessageParams::Message::Preferences?,
          providers: ::Hash[Symbol, Courier::SendMessageParams::Message::Provider]?,
          routing: Courier::SendMessageParams::Message::Routing?,
          template: String?,
          timeout: Courier::SendMessageParams::Message::Timeout?,
          to: Courier::Models::SendMessageParams::Message::to?
        }

      class Message < Courier::Internal::Type::BaseModel
        attr_accessor brand_id: String?

        attr_accessor channels: ::Hash[Symbol, Courier::SendMessageParams::Message::Channel]?

        attr_reader content: Courier::Models::SendMessageParams::Message::content?

        def content=: (
          Courier::Models::SendMessageParams::Message::content
        ) -> Courier::Models::SendMessageParams::Message::content

        attr_accessor context: Courier::MessageContext?

        attr_accessor data: ::Hash[Symbol, top]?

        attr_accessor delay: Courier::SendMessageParams::Message::Delay?

        attr_accessor expiry: Courier::SendMessageParams::Message::Expiry?

        attr_accessor metadata: Courier::SendMessageParams::Message::Metadata?

        attr_accessor preferences: Courier::SendMessageParams::Message::Preferences?

        attr_accessor providers: ::Hash[Symbol, Courier::SendMessageParams::Message::Provider]?

        attr_accessor routing: Courier::SendMessageParams::Message::Routing?

        attr_accessor template: String?

        attr_accessor timeout: Courier::SendMessageParams::Message::Timeout?

        attr_accessor to: Courier::Models::SendMessageParams::Message::to?

        def initialize: (
          ?brand_id: String?,
          ?channels: ::Hash[Symbol, Courier::SendMessageParams::Message::Channel]?,
          ?content: Courier::Models::SendMessageParams::Message::content,
          ?context: Courier::MessageContext?,
          ?data: ::Hash[Symbol, top]?,
          ?delay: Courier::SendMessageParams::Message::Delay?,
          ?expiry: Courier::SendMessageParams::Message::Expiry?,
          ?metadata: Courier::SendMessageParams::Message::Metadata?,
          ?preferences: Courier::SendMessageParams::Message::Preferences?,
          ?providers: ::Hash[Symbol, Courier::SendMessageParams::Message::Provider]?,
          ?routing: Courier::SendMessageParams::Message::Routing?,
          ?template: String?,
          ?timeout: Courier::SendMessageParams::Message::Timeout?,
          ?to: Courier::Models::SendMessageParams::Message::to?
        ) -> void

        def to_hash: -> {
          brand_id: String?,
          channels: ::Hash[Symbol, Courier::SendMessageParams::Message::Channel]?,
          content: Courier::Models::SendMessageParams::Message::content,
          context: Courier::MessageContext?,
          data: ::Hash[Symbol, top]?,
          delay: Courier::SendMessageParams::Message::Delay?,
          expiry: Courier::SendMessageParams::Message::Expiry?,
          metadata: Courier::SendMessageParams::Message::Metadata?,
          preferences: Courier::SendMessageParams::Message::Preferences?,
          providers: ::Hash[Symbol, Courier::SendMessageParams::Message::Provider]?,
          routing: Courier::SendMessageParams::Message::Routing?,
          template: String?,
          timeout: Courier::SendMessageParams::Message::Timeout?,
          to: Courier::Models::SendMessageParams::Message::to?
        }

        type channel =
          {
            brand_id: String?,
            if_: String?,
            metadata: Courier::SendMessageParams::Message::Channel::Metadata?,
            override: ::Hash[Symbol, top]?,
            providers: ::Array[String]?,
            routing_method: Courier::Models::SendMessageParams::Message::Channel::routing_method?,
            timeouts: Courier::SendMessageParams::Message::Channel::Timeouts?
          }

        class Channel < Courier::Internal::Type::BaseModel
          attr_accessor brand_id: String?

          attr_accessor if_: String?

          attr_accessor metadata: Courier::SendMessageParams::Message::Channel::Metadata?

          attr_accessor override: ::Hash[Symbol, top]?

          attr_accessor providers: ::Array[String]?

          attr_accessor routing_method: Courier::Models::SendMessageParams::Message::Channel::routing_method?

          attr_accessor timeouts: Courier::SendMessageParams::Message::Channel::Timeouts?

          def initialize: (
            ?brand_id: String?,
            ?if_: String?,
            ?metadata: Courier::SendMessageParams::Message::Channel::Metadata?,
            ?override: ::Hash[Symbol, top]?,
            ?providers: ::Array[String]?,
            ?routing_method: Courier::Models::SendMessageParams::Message::Channel::routing_method?,
            ?timeouts: Courier::SendMessageParams::Message::Channel::Timeouts?
          ) -> void

          def to_hash: -> {
            brand_id: String?,
            if_: String?,
            metadata: Courier::SendMessageParams::Message::Channel::Metadata?,
            override: ::Hash[Symbol, top]?,
            providers: ::Array[String]?,
            routing_method: Courier::Models::SendMessageParams::Message::Channel::routing_method?,
            timeouts: Courier::SendMessageParams::Message::Channel::Timeouts?
          }

          type metadata = { utm: Courier::Utm? }

          class Metadata < Courier::Internal::Type::BaseModel
            attr_accessor utm: Courier::Utm?

            def initialize: (?utm: Courier::Utm?) -> void

            def to_hash: -> { utm: Courier::Utm? }
          end

          type routing_method = :all | :single

          module RoutingMethod
            extend Courier::Internal::Type::Enum

            ALL: :all
            SINGLE: :single

            def self?.values: -> ::Array[Courier::Models::SendMessageParams::Message::Channel::routing_method]
          end

          type timeouts = { channel: Integer?, provider: Integer? }

          class Timeouts < Courier::Internal::Type::BaseModel
            attr_accessor channel: Integer?

            attr_accessor provider: Integer?

            def initialize: (?channel: Integer?, ?provider: Integer?) -> void

            def to_hash: -> { channel: Integer?, provider: Integer? }
          end
        end

        type content =
          Courier::ElementalContentSugar | Courier::Tenants::ElementalContent

        module Content
          extend Courier::Internal::Type::Union

          def self?.variants: -> ::Array[Courier::Models::SendMessageParams::Message::content]
        end

        type delay = { duration: Integer?, until_: String? }

        class Delay < Courier::Internal::Type::BaseModel
          attr_accessor duration: Integer?

          attr_accessor until_: String?

          def initialize: (?duration: Integer?, ?until_: String?) -> void

          def to_hash: -> { duration: Integer?, until_: String? }
        end

        type expiry =
          {
            expires_in: Courier::Models::SendMessageParams::Message::Expiry::expires_in,
            expires_at: String?
          }

        class Expiry < Courier::Internal::Type::BaseModel
          attr_accessor expires_in: Courier::Models::SendMessageParams::Message::Expiry::expires_in

          attr_accessor expires_at: String?

          def initialize: (
            expires_in: Courier::Models::SendMessageParams::Message::Expiry::expires_in,
            ?expires_at: String?
          ) -> void

          def to_hash: -> {
            expires_in: Courier::Models::SendMessageParams::Message::Expiry::expires_in,
            expires_at: String?
          }

          type expires_in = String | Integer

          module ExpiresIn
            extend Courier::Internal::Type::Union

            def self?.variants: -> ::Array[Courier::Models::SendMessageParams::Message::Expiry::expires_in]
          end
        end

        type metadata =
          {
            event: String?,
            tags: ::Array[String]?,
            trace_id: String?,
            utm: Courier::Utm?
          }

        class Metadata < Courier::Internal::Type::BaseModel
          attr_accessor event: String?

          attr_accessor tags: ::Array[String]?

          attr_accessor trace_id: String?

          attr_accessor utm: Courier::Utm?

          def initialize: (
            ?event: String?,
            ?tags: ::Array[String]?,
            ?trace_id: String?,
            ?utm: Courier::Utm?
          ) -> void

          def to_hash: -> {
            event: String?,
            tags: ::Array[String]?,
            trace_id: String?,
            utm: Courier::Utm?
          }
        end

        type preferences = { subscription_topic_id: String }

        class Preferences < Courier::Internal::Type::BaseModel
          attr_accessor subscription_topic_id: String

          def initialize: (subscription_topic_id: String) -> void

          def to_hash: -> { subscription_topic_id: String }
        end

        type provider =
          {
            if_: String?,
            metadata: Courier::SendMessageParams::Message::Provider::Metadata?,
            override: ::Hash[Symbol, top]?,
            timeouts: Integer?
          }

        class Provider < Courier::Internal::Type::BaseModel
          attr_accessor if_: String?

          attr_accessor metadata: Courier::SendMessageParams::Message::Provider::Metadata?

          attr_accessor override: ::Hash[Symbol, top]?

          attr_accessor timeouts: Integer?

          def initialize: (
            ?if_: String?,
            ?metadata: Courier::SendMessageParams::Message::Provider::Metadata?,
            ?override: ::Hash[Symbol, top]?,
            ?timeouts: Integer?
          ) -> void

          def to_hash: -> {
            if_: String?,
            metadata: Courier::SendMessageParams::Message::Provider::Metadata?,
            override: ::Hash[Symbol, top]?,
            timeouts: Integer?
          }

          type metadata = { utm: Courier::Utm? }

          class Metadata < Courier::Internal::Type::BaseModel
            attr_accessor utm: Courier::Utm?

            def initialize: (?utm: Courier::Utm?) -> void

            def to_hash: -> { utm: Courier::Utm? }
          end
        end

        type routing =
          {
            channels: ::Array[Courier::Models::message_routing_channel],
            method_: Courier::Models::SendMessageParams::Message::Routing::method_
          }

        class Routing < Courier::Internal::Type::BaseModel
          attr_accessor channels: ::Array[Courier::Models::message_routing_channel]

          attr_accessor method_: Courier::Models::SendMessageParams::Message::Routing::method_

          def initialize: (
            channels: ::Array[Courier::Models::message_routing_channel],
            method_: Courier::Models::SendMessageParams::Message::Routing::method_
          ) -> void

          def to_hash: -> {
            channels: ::Array[Courier::Models::message_routing_channel],
            method_: Courier::Models::SendMessageParams::Message::Routing::method_
          }

          type method_ = :all | :single

          module Method
            extend Courier::Internal::Type::Enum

            ALL: :all
            SINGLE: :single

            def self?.values: -> ::Array[Courier::Models::SendMessageParams::Message::Routing::method_]
          end
        end

        type timeout =
          {
            channel: ::Hash[Symbol, Integer]?,
            criteria: Courier::Models::SendMessageParams::Message::Timeout::criteria?,
            escalation: Integer?,
            message: Integer?,
            provider: ::Hash[Symbol, Integer]?
          }

        class Timeout < Courier::Internal::Type::BaseModel
          attr_accessor channel: ::Hash[Symbol, Integer]?

          attr_accessor criteria: Courier::Models::SendMessageParams::Message::Timeout::criteria?

          attr_accessor escalation: Integer?

          attr_accessor message: Integer?

          attr_accessor provider: ::Hash[Symbol, Integer]?

          def initialize: (
            ?channel: ::Hash[Symbol, Integer]?,
            ?criteria: Courier::Models::SendMessageParams::Message::Timeout::criteria?,
            ?escalation: Integer?,
            ?message: Integer?,
            ?provider: ::Hash[Symbol, Integer]?
          ) -> void

          def to_hash: -> {
            channel: ::Hash[Symbol, Integer]?,
            criteria: Courier::Models::SendMessageParams::Message::Timeout::criteria?,
            escalation: Integer?,
            message: Integer?,
            provider: ::Hash[Symbol, Integer]?
          }

          type criteria = :"no-escalation" | :delivered | :viewed | :engaged

          module Criteria
            extend Courier::Internal::Type::Enum

            NO_ESCALATION: :"no-escalation"
            DELIVERED: :delivered
            VIEWED: :viewed
            ENGAGED: :engaged

            def self?.values: -> ::Array[Courier::Models::SendMessageParams::Message::Timeout::criteria]
          end
        end

        type to =
          Courier::UserRecipient
          | Courier::ListRecipient
          | ::Array[Courier::Models::recipient]

        module To
          extend Courier::Internal::Type::Union

          def self?.variants: -> ::Array[Courier::Models::SendMessageParams::Message::to]

          RecipientArray: Courier::Internal::Type::Converter
        end
      end
    end
  end
end
