module Courier
  module Models
    type tenant_template_input =
      {
        content: Courier::ElementalContent,
        channels: Courier::Models::message_channels,
        providers: Courier::Models::message_providers,
        routing: Courier::MessageRouting
      }

    class TenantTemplateInput < Courier::Internal::Type::BaseModel
      attr_accessor content: Courier::ElementalContent

      attr_reader channels: Courier::Models::message_channels?

      def channels=: (
        Courier::Models::message_channels
      ) -> Courier::Models::message_channels

      attr_reader providers: Courier::Models::message_providers?

      def providers=: (
        Courier::Models::message_providers
      ) -> Courier::Models::message_providers

      attr_reader routing: Courier::MessageRouting?

      def routing=: (Courier::MessageRouting) -> Courier::MessageRouting

      def initialize: (
        content: Courier::ElementalContent,
        ?channels: Courier::Models::message_channels,
        ?providers: Courier::Models::message_providers,
        ?routing: Courier::MessageRouting
      ) -> void

      def to_hash: -> {
        content: Courier::ElementalContent,
        channels: Courier::Models::message_channels,
        providers: Courier::Models::message_providers,
        routing: Courier::MessageRouting
      }
    end
  end
end
