module Courier
  module Models
    type tenant_list_params =
      { cursor: String?, limit: Integer?, parent_tenant_id: String? }
      & Courier::Internal::Type::request_parameters

    class TenantListParams < Courier::Internal::Type::BaseModel
      extend Courier::Internal::Type::RequestParameters::Converter
      include Courier::Internal::Type::RequestParameters

      attr_accessor cursor: String?

      attr_accessor limit: Integer?

      attr_accessor parent_tenant_id: String?

      def initialize: (
        ?cursor: String?,
        ?limit: Integer?,
        ?parent_tenant_id: String?,
        ?request_options: Courier::request_opts
      ) -> void

      def to_hash: -> {
        cursor: String?,
        limit: Integer?,
        parent_tenant_id: String?,
        request_options: Courier::RequestOptions
      }
    end
  end
end
