module Courier
  module Models
    type workspace_preference_topic_get_response =
      {
        id: String,
        allowed_preferences: ::Array[Courier::Models::WorkspacePreferenceTopicGetResponse::allowed_preference],
        created: String,
        default_status: Courier::Models::WorkspacePreferenceTopicGetResponse::default_status,
        include_unsubscribe_header: bool,
        name: String,
        routing_options: ::Array[Courier::Models::channel_classification],
        topic_data: ::Hash[Symbol, top],
        updated: String,
        creator: String?,
        updater: String?
      }

    class WorkspacePreferenceTopicGetResponse < Courier::Internal::Type::BaseModel
      attr_accessor id: String

      attr_accessor allowed_preferences: ::Array[Courier::Models::WorkspacePreferenceTopicGetResponse::allowed_preference]

      attr_accessor created: String

      attr_accessor default_status: Courier::Models::WorkspacePreferenceTopicGetResponse::default_status

      attr_accessor include_unsubscribe_header: bool

      attr_accessor name: String

      attr_accessor routing_options: ::Array[Courier::Models::channel_classification]

      attr_accessor topic_data: ::Hash[Symbol, top]

      attr_accessor updated: String

      attr_accessor creator: String?

      attr_accessor updater: String?

      def initialize: (
        id: String,
        allowed_preferences: ::Array[Courier::Models::WorkspacePreferenceTopicGetResponse::allowed_preference],
        created: String,
        default_status: Courier::Models::WorkspacePreferenceTopicGetResponse::default_status,
        include_unsubscribe_header: bool,
        name: String,
        routing_options: ::Array[Courier::Models::channel_classification],
        topic_data: ::Hash[Symbol, top],
        updated: String,
        ?creator: String?,
        ?updater: String?
      ) -> void

      def to_hash: -> {
        id: String,
        allowed_preferences: ::Array[Courier::Models::WorkspacePreferenceTopicGetResponse::allowed_preference],
        created: String,
        default_status: Courier::Models::WorkspacePreferenceTopicGetResponse::default_status,
        include_unsubscribe_header: bool,
        name: String,
        routing_options: ::Array[Courier::Models::channel_classification],
        topic_data: ::Hash[Symbol, top],
        updated: String,
        creator: String?,
        updater: String?
      }

      type allowed_preference = :snooze | :channel_preferences

      module AllowedPreference
        extend Courier::Internal::Type::Enum

        SNOOZE: :snooze
        CHANNEL_PREFERENCES: :channel_preferences

        def self?.values: -> ::Array[Courier::Models::WorkspacePreferenceTopicGetResponse::allowed_preference]
      end

      type default_status = :OPTED_OUT | :OPTED_IN | :REQUIRED

      module DefaultStatus
        extend Courier::Internal::Type::Enum

        OPTED_OUT: :OPTED_OUT
        OPTED_IN: :OPTED_IN
        REQUIRED: :REQUIRED

        def self?.values: -> ::Array[Courier::Models::WorkspacePreferenceTopicGetResponse::default_status]
      end
    end
  end
end
