module Courier
  module Models
    type workspace_preference_get_response =
      {
        id: String,
        created: String,
        has_custom_routing: bool,
        name: String,
        routing_options: ::Array[Courier::Models::channel_classification],
        topics: ::Array[Courier::WorkspacePreferenceTopicGetResponse],
        creator: String?,
        updated: String?,
        updater: String?
      }

    class WorkspacePreferenceGetResponse < Courier::Internal::Type::BaseModel
      attr_accessor id: String

      attr_accessor created: String

      attr_accessor has_custom_routing: bool

      attr_accessor name: String

      attr_accessor routing_options: ::Array[Courier::Models::channel_classification]

      attr_accessor topics: ::Array[Courier::WorkspacePreferenceTopicGetResponse]

      attr_accessor creator: String?

      attr_accessor updated: String?

      attr_accessor updater: String?

      def initialize: (
        id: String,
        created: String,
        has_custom_routing: bool,
        name: String,
        routing_options: ::Array[Courier::Models::channel_classification],
        topics: ::Array[Courier::WorkspacePreferenceTopicGetResponse],
        ?creator: String?,
        ?updated: String?,
        ?updater: String?
      ) -> void

      def to_hash: -> {
        id: String,
        created: String,
        has_custom_routing: bool,
        name: String,
        routing_options: ::Array[Courier::Models::channel_classification],
        topics: ::Array[Courier::WorkspacePreferenceTopicGetResponse],
        creator: String?,
        updated: String?,
        updater: String?
      }
    end
  end
end
