module Courier
  module Models
    type workspace_preference_create_params =
      { idempotency_key: String, x_idempotency_expiration: String }
      & Courier::Internal::Type::request_parameters

    class WorkspacePreferenceCreateParams < Courier::Models::WorkspacePreferenceCreateRequest
      extend Courier::Internal::Type::RequestParameters::Converter
      include Courier::Internal::Type::RequestParameters

      def idempotency_key: -> String?

      def idempotency_key=: (String _) -> String

      def x_idempotency_expiration: -> String?

      def x_idempotency_expiration=: (String _) -> String

      def initialize: (
        ?idempotency_key: String,
        ?x_idempotency_expiration: String,
        ?request_options: Courier::request_opts
      ) -> void

      def to_hash: -> {
        idempotency_key: String,
        x_idempotency_expiration: String,
        request_options: Courier::RequestOptions
      }
    end
  end
end
