module Courier
  module Models
    module Profiles
      type list_subscribe_response =
        { status: Courier::Models::Profiles::ListSubscribeResponse::status }

      class ListSubscribeResponse < Courier::Internal::Type::BaseModel
        attr_accessor status: Courier::Models::Profiles::ListSubscribeResponse::status

        def initialize: (
          status: Courier::Models::Profiles::ListSubscribeResponse::status
        ) -> void

        def to_hash: -> {
          status: Courier::Models::Profiles::ListSubscribeResponse::status
        }

        type status = :SUCCESS

        module Status
          extend Courier::Internal::Type::Enum

          SUCCESS: :SUCCESS

          def self?.values: -> ::Array[Courier::Models::Profiles::ListSubscribeResponse::status]
        end
      end
    end
  end
end
