module Courier
  module Models
    module Automations
      type merge_algorithm = :replace | :none | :overwrite | :"soft-merge"

      module MergeAlgorithm
        extend Courier::Internal::Type::Enum

        REPLACE: :replace
        NONE: :none
        OVERWRITE: :overwrite
        SOFT_MERGE: :"soft-merge"

        def self?.values: -> ::Array[Courier::Models::Automations::merge_algorithm]
      end
    end
  end
end
