module Courier
  module Models
    module PreferenceSections
      type topic_create_params =
        { section_id: String } & Courier::Internal::Type::request_parameters

      class TopicCreateParams < Courier::Models::PreferenceTopicCreateRequest
        extend Courier::Internal::Type::RequestParameters::Converter
        include Courier::Internal::Type::RequestParameters

        def section_id: -> String

        def section_id=: (String _) -> String

        def initialize: (
          section_id: String,
          ?request_options: Courier::request_opts
        ) -> void

        def to_hash: -> {
          section_id: String,
          request_options: Courier::RequestOptions
        }
      end
    end
  end
end
