module Courier
  module Models
    module Notifications
      type check_list_response = { checks: ::Array[Courier::Check] }

      class CheckListResponse < Courier::Internal::Type::BaseModel
        attr_accessor checks: ::Array[Courier::Check]

        def initialize: (checks: ::Array[Courier::Check]) -> void

        def to_hash: -> { checks: ::Array[Courier::Check] }
      end
    end
  end
end
