module Courier
  module Models
    module Notifications
      type check_delete_params =
        { id: String, submission_id: String }
        & Courier::Internal::Type::request_parameters

      class CheckDeleteParams < Courier::Internal::Type::BaseModel
        extend Courier::Internal::Type::RequestParameters::Converter
        include Courier::Internal::Type::RequestParameters

        attr_accessor id: String

        attr_accessor submission_id: String

        def initialize: (
          id: String,
          submission_id: String,
          ?request_options: Courier::request_opts
        ) -> void

        def to_hash: -> {
          id: String,
          submission_id: String,
          request_options: Courier::RequestOptions
        }
      end
    end
  end
end
