module Courier
  module Models
    module Notifications
      type check_update_params =
        { id: String, checks: ::Array[Courier::BaseCheck] }
        & Courier::Internal::Type::request_parameters

      class CheckUpdateParams < Courier::Internal::Type::BaseModel
        extend Courier::Internal::Type::RequestParameters::Converter
        include Courier::Internal::Type::RequestParameters

        attr_accessor id: String

        attr_accessor checks: ::Array[Courier::BaseCheck]

        def initialize: (
          id: String,
          checks: ::Array[Courier::BaseCheck],
          ?request_options: Courier::request_opts
        ) -> void

        def to_hash: -> {
          id: String,
          checks: ::Array[Courier::BaseCheck],
          request_options: Courier::RequestOptions
        }
      end
    end
  end
end
