module Courier
  module Models
    module Tenants
      type elemental_content =
        {
          elements: ::Array[Courier::Models::Tenants::elemental_node],
          version: String,
          brand: top
        }

      class ElementalContent < Courier::Internal::Type::BaseModel
        attr_accessor elements: ::Array[Courier::Models::Tenants::elemental_node]

        attr_accessor version: String

        attr_reader brand: top?

        def brand=: (top) -> top

        def initialize: (
          elements: ::Array[Courier::Models::Tenants::elemental_node],
          version: String,
          ?brand: top
        ) -> void

        def to_hash: -> {
          elements: ::Array[Courier::Models::Tenants::elemental_node],
          version: String,
          brand: top
        }
      end
    end
  end
end
