module Courier
  module Models
    module Tenants
      type elemental_content =
        {
          elements: ::Array[Courier::Models::elemental_node],
          version: String,
          brand: String?
        }

      class ElementalContent < Courier::Internal::Type::BaseModel
        attr_accessor elements: ::Array[Courier::Models::elemental_node]

        attr_accessor version: String

        attr_accessor brand: String?

        def initialize: (
          elements: ::Array[Courier::Models::elemental_node],
          version: String,
          ?brand: String?
        ) -> void

        def to_hash: -> {
          elements: ::Array[Courier::Models::elemental_node],
          version: String,
          brand: String?
        }
      end
    end
  end
end
