module Courier
  module Resources
    class Tenants
      class DefaultPreferences
        class Items
          def update: (
            String topic_id,
            tenant_id: String,
            status: Courier::Models::Tenants::DefaultPreferences::SubscriptionTopicNew::status,
            ?custom_routing: ::Array[Courier::Models::Tenants::DefaultPreferences::channel_classification]?,
            ?has_custom_routing: bool?,
            ?request_options: Courier::request_opts
          ) -> nil

          def delete: (
            String topic_id,
            tenant_id: String,
            ?request_options: Courier::request_opts
          ) -> nil

          def initialize: (client: Courier::Client) -> void
        end
      end
    end
  end
end
