module Trycourier
  module Models
    module Notifications
      type check_list_params =
        { id: String } & Trycourier::Internal::Type::request_parameters

      class CheckListParams < Trycourier::Internal::Type::BaseModel
        extend Trycourier::Internal::Type::RequestParameters::Converter
        include Trycourier::Internal::Type::RequestParameters

        attr_accessor id: String

        def initialize: (
          id: String,
          ?request_options: Trycourier::request_opts
        ) -> void

        def to_hash: -> {
          id: String,
          request_options: Trycourier::RequestOptions
        }
      end
    end
  end
end
