module Trycourier
  module Models
    module Notifications
      type check_update_response = { checks: ::Array[Trycourier::Check] }

      class CheckUpdateResponse < Trycourier::Internal::Type::BaseModel
        attr_accessor checks: ::Array[Trycourier::Check]

        def initialize: (checks: ::Array[Trycourier::Check]) -> void

        def to_hash: -> { checks: ::Array[Trycourier::Check] }
      end
    end
  end
end
