module Courier
  module Models
    module Lists
      type subscription_add_params =
        { recipients: ::Array[Courier::PutSubscriptionsRecipient] }
        & Courier::Internal::Type::request_parameters

      class SubscriptionAddParams < Courier::Internal::Type::BaseModel
        extend Courier::Internal::Type::RequestParameters::Converter
        include Courier::Internal::Type::RequestParameters

        attr_accessor recipients: ::Array[Courier::PutSubscriptionsRecipient]

        def initialize: (
          recipients: ::Array[Courier::PutSubscriptionsRecipient],
          ?request_options: Courier::request_opts
        ) -> void

        def to_hash: -> {
          recipients: ::Array[Courier::PutSubscriptionsRecipient],
          request_options: Courier::RequestOptions
        }
      end
    end
  end
end
