module Courier
  module Models
    module Lists
      type subscription_unsubscribe_user_params =
        { list_id: String } & Courier::Internal::Type::request_parameters

      class SubscriptionUnsubscribeUserParams < Courier::Internal::Type::BaseModel
        extend Courier::Internal::Type::RequestParameters::Converter
        include Courier::Internal::Type::RequestParameters

        attr_accessor list_id: String

        def initialize: (
          list_id: String,
          ?request_options: Courier::request_opts
        ) -> void

        def to_hash: -> {
          list_id: String,
          request_options: Courier::RequestOptions
        }
      end
    end
  end
end
