module Courier
  class Client < Courier::Internal::Transport::BaseClient
    DEFAULT_MAX_RETRIES: 2

    DEFAULT_TIMEOUT_IN_SECONDS: Float

    DEFAULT_INITIAL_RETRY_DELAY: Float

    DEFAULT_MAX_RETRY_DELAY: Float

    attr_reader api_key: String

    attr_reader send_: Courier::Resources::Send

    attr_reader tenants: Courier::Resources::Tenants

    attr_reader audiences: Courier::Resources::Audiences

    attr_reader bulk: Courier::Resources::Bulk

    attr_reader users: Courier::Resources::Users

    attr_reader audit_events: Courier::Resources::AuditEvents

    attr_reader automations: Courier::Resources::Automations

    attr_reader brands: Courier::Resources::Brands

    attr_reader lists: Courier::Resources::Lists

    attr_reader messages: Courier::Resources::Messages

    attr_reader notifications: Courier::Resources::Notifications

    attr_reader auth: Courier::Resources::Auth

    attr_reader inbound: Courier::Resources::Inbound

    attr_reader requests: Courier::Resources::Requests

    attr_reader profiles: Courier::Resources::Profiles

    attr_reader translations: Courier::Resources::Translations

    private def auth_headers: -> ::Hash[String, String]

    def initialize: (
      ?api_key: String?,
      ?base_url: String?,
      ?max_retries: Integer,
      ?timeout: Float,
      ?initial_retry_delay: Float,
      ?max_retry_delay: Float
    ) -> void
  end
end
