module Courier
  module Alignment = Courier::Models::Alignment

  class ElementalBaseNode = Courier::Models::ElementalBaseNode

  class ElementalChannelNode = Courier::Models::ElementalChannelNode

  module ElementalNode = Courier::Models::ElementalNode

  class MessageContext = Courier::Models::MessageContext

  class MessageRouting = Courier::Models::MessageRouting

  module MessageRoutingChannel = Courier::Models::MessageRoutingChannel

  class Preference = Courier::Models::Preference

  class Recipient = Courier::Models::Recipient

  class SendMessageParams = Courier::Models::SendMessageParams

  module TextStyle = Courier::Models::TextStyle

  class Utm = Courier::Models::Utm
end
