module Courier
  class ElementalChannelNode = Courier::Models::ElementalChannelNode

  class ElementalGroupNode = Courier::Models::ElementalGroupNode

  module ElementalNode = Courier::Models::ElementalNode

  class MessageContext = Courier::Models::MessageContext

  class MessageRouting = Courier::Models::MessageRouting

  module MessageRoutingChannel = Courier::Models::MessageRoutingChannel

  class Preference = Courier::Models::Preference

  class Recipient = Courier::Models::Recipient

  class SendMessageParams = Courier::Models::SendMessageParams

  class Utm = Courier::Models::Utm
end
