module Courier
  module Models
    module Users
      type preference_retrieve_response =
        { items: ::Array[Courier::TopicPreference], paging: Courier::Paging }

      class PreferenceRetrieveResponse < Courier::Internal::Type::BaseModel
        attr_accessor items: ::Array[Courier::TopicPreference]

        attr_accessor paging: Courier::Paging

        def initialize: (
          items: ::Array[Courier::TopicPreference],
          paging: Courier::Paging
        ) -> void

        def to_hash: -> {
          items: ::Array[Courier::TopicPreference],
          paging: Courier::Paging
        }
      end
    end
  end
end
