module Courier
  module Models
    module Users
      type preference_retrieve_topic_response =
        { topic: Courier::TopicPreference }

      class PreferenceRetrieveTopicResponse < Courier::Internal::Type::BaseModel
        attr_accessor topic: Courier::TopicPreference

        def initialize: (topic: Courier::TopicPreference) -> void

        def to_hash: -> { topic: Courier::TopicPreference }
      end
    end
  end
end
