module Courier
  module Models
    module Users
      type tenant_add_multiple_params =
        { tenants: ::Array[Courier::TenantAssociation] }
        & Courier::Internal::Type::request_parameters

      class TenantAddMultipleParams < Courier::Internal::Type::BaseModel
        extend Courier::Internal::Type::RequestParameters::Converter
        include Courier::Internal::Type::RequestParameters

        attr_accessor tenants: ::Array[Courier::TenantAssociation]

        def initialize: (
          tenants: ::Array[Courier::TenantAssociation],
          ?request_options: Courier::request_opts
        ) -> void

        def to_hash: -> {
          tenants: ::Array[Courier::TenantAssociation],
          request_options: Courier::RequestOptions
        }
      end
    end
  end
end
