module Courier
  module Models
    module Users
      type token_add_multiple_params =
        {  } & Courier::Internal::Type::request_parameters

      class TokenAddMultipleParams < Courier::Internal::Type::BaseModel
        extend Courier::Internal::Type::RequestParameters::Converter
        include Courier::Internal::Type::RequestParameters

        def initialize: (?request_options: Courier::request_opts) -> void

        def to_hash: -> { request_options: Courier::RequestOptions }
      end
    end
  end
end
