module Courier
  module Models
    module Users
      type token_update_params =
        {
          user_id: String,
          patch: ::Array[Courier::Users::TokenUpdateParams::Patch]
        }
        & Courier::Internal::Type::request_parameters

      class TokenUpdateParams < Courier::Internal::Type::BaseModel
        extend Courier::Internal::Type::RequestParameters::Converter
        include Courier::Internal::Type::RequestParameters

        attr_accessor user_id: String

        attr_accessor patch: ::Array[Courier::Users::TokenUpdateParams::Patch]

        def initialize: (
          user_id: String,
          patch: ::Array[Courier::Users::TokenUpdateParams::Patch],
          ?request_options: Courier::request_opts
        ) -> void

        def to_hash: -> {
          user_id: String,
          patch: ::Array[Courier::Users::TokenUpdateParams::Patch],
          request_options: Courier::RequestOptions
        }

        type patch = { op: String, path: String, value: String? }

        class Patch < Courier::Internal::Type::BaseModel
          attr_accessor op: String

          attr_accessor path: String

          attr_accessor value: String?

          def initialize: (op: String, path: String, ?value: String?) -> void

          def to_hash: -> { op: String, path: String, value: String? }
        end
      end
    end
  end
end
