module Courier
  module Models
    module Users
      type token_delete_params =
        { user_id: String } & Courier::Internal::Type::request_parameters

      class TokenDeleteParams < Courier::Internal::Type::BaseModel
        extend Courier::Internal::Type::RequestParameters::Converter
        include Courier::Internal::Type::RequestParameters

        attr_accessor user_id: String

        def initialize: (
          user_id: String,
          ?request_options: Courier::request_opts
        ) -> void

        def to_hash: -> {
          user_id: String,
          request_options: Courier::RequestOptions
        }
      end
    end
  end
end
