module Courier
  module Resources
    class Lists
      class Subscriptions
        def list: (
          String list_id,
          ?cursor: String?,
          ?request_options: Courier::request_opts
        ) -> Courier::Models::Lists::SubscriptionListResponse

        def add: (
          String list_id,
          recipients: ::Array[Courier::PutSubscriptionsRecipient],
          ?request_options: Courier::request_opts
        ) -> nil

        def subscribe: (
          String list_id,
          recipients: ::Array[Courier::PutSubscriptionsRecipient],
          ?request_options: Courier::request_opts
        ) -> nil

        def subscribe_user: (
          String user_id,
          list_id: String,
          ?preferences: Courier::RecipientPreferences?,
          ?request_options: Courier::request_opts
        ) -> nil

        def unsubscribe_user: (
          String user_id,
          list_id: String,
          ?request_options: Courier::request_opts
        ) -> nil

        def initialize: (client: Courier::Client) -> void
      end
    end
  end
end
