module Courier
  module Resources
    class Users
      class Preferences
        def retrieve: (
          String user_id,
          ?tenant_id: String?,
          ?request_options: Courier::request_opts
        ) -> Courier::Models::Users::PreferenceRetrieveResponse

        def retrieve_topic: (
          String topic_id,
          user_id: String,
          ?tenant_id: String?,
          ?request_options: Courier::request_opts
        ) -> Courier::Models::Users::PreferenceRetrieveTopicResponse

        def update_or_create_topic: (
          String topic_id,
          user_id: String,
          topic: Courier::Users::PreferenceUpdateOrCreateTopicParams::Topic,
          ?tenant_id: String?,
          ?request_options: Courier::request_opts
        ) -> Courier::Models::Users::PreferenceUpdateOrCreateTopicResponse

        def initialize: (client: Courier::Client) -> void
      end
    end
  end
end
