module Courier
  module Resources
    class Users
      class Tokens
        def retrieve: (
          String token,
          user_id: String,
          ?request_options: Courier::request_opts
        ) -> Courier::Models::Users::TokenRetrieveResponse

        def update: (
          String token,
          user_id: String,
          patch: ::Array[Courier::Users::TokenUpdateParams::Patch],
          ?request_options: Courier::request_opts
        ) -> nil

        def list: (
          String user_id,
          ?request_options: Courier::request_opts
        ) -> Courier::Models::Users::token_list_response

        def delete: (
          String token,
          user_id: String,
          ?request_options: Courier::request_opts
        ) -> nil

        def add_multiple: (
          String user_id,
          ?request_options: Courier::request_opts
        ) -> nil

        def add_single: (
          String path_token,
          user_id: String,
          provider_key: Courier::Models::UserToken::provider_key,
          ?body_token: String?,
          ?device: Courier::UserToken::Device?,
          ?expiry_date: Courier::Models::UserToken::expiry_date?,
          ?properties: top,
          ?tracking: Courier::UserToken::Tracking?,
          ?request_options: Courier::request_opts
        ) -> nil

        def initialize: (client: Courier::Client) -> void
      end
    end
  end
end
