module Courier
  module Resources
    class Audiences
      def retrieve: (
        String audience_id,
        ?request_options: Courier::request_opts
      ) -> Courier::Audience

      def update: (
        String audience_id,
        ?description: String?,
        ?filter: Courier::Filter?,
        ?name: String?,
        ?request_options: Courier::request_opts
      ) -> Courier::Models::AudienceUpdateResponse

      def list: (
        ?cursor: String?,
        ?request_options: Courier::request_opts
      ) -> Courier::Models::AudienceListResponse

      def delete: (
        String audience_id,
        ?request_options: Courier::request_opts
      ) -> nil

      def list_members: (
        String audience_id,
        ?cursor: String?,
        ?request_options: Courier::request_opts
      ) -> Courier::Models::AudienceListMembersResponse

      def initialize: (client: Courier::Client) -> void
    end
  end
end
