module Courier
  module Resources
    class Brands
      def create: (
        name: String,
        ?id: String?,
        ?settings: Courier::BrandSettings?,
        ?snippets: Courier::BrandSnippets?,
        ?request_options: Courier::request_opts
      ) -> Courier::Brand

      def retrieve: (
        String brand_id,
        ?request_options: Courier::request_opts
      ) -> Courier::Brand

      def update: (
        String brand_id,
        name: String,
        ?settings: Courier::BrandSettings?,
        ?snippets: Courier::BrandSnippets?,
        ?request_options: Courier::request_opts
      ) -> Courier::Brand

      def list: (
        ?cursor: String?,
        ?request_options: Courier::request_opts
      ) -> Courier::Models::BrandListResponse

      def delete: (
        String brand_id,
        ?request_options: Courier::request_opts
      ) -> nil

      def initialize: (client: Courier::Client) -> void
    end
  end
end
