module Courier
  module Resources
    class Bulk
      def add_users: (
        String job_id,
        users: ::Array[Courier::InboundBulkMessageUser],
        ?request_options: Courier::request_opts
      ) -> nil

      def create_job: (
        message: Courier::Models::inbound_bulk_message,
        ?request_options: Courier::request_opts
      ) -> Courier::Models::BulkCreateJobResponse

      def list_users: (
        String job_id,
        ?cursor: String?,
        ?request_options: Courier::request_opts
      ) -> Courier::Models::BulkListUsersResponse

      def retrieve_job: (
        String job_id,
        ?request_options: Courier::request_opts
      ) -> Courier::Models::BulkRetrieveJobResponse

      def run_job: (
        String job_id,
        ?request_options: Courier::request_opts
      ) -> nil

      def initialize: (client: Courier::Client) -> void
    end
  end
end
