module Courier
  module Resources
    class Journeys
      attr_reader templates: Courier::Resources::Journeys::Templates

      def create: (
        name: String,
        nodes: ::Array[Courier::Models::journey_node],
        ?enabled: bool,
        ?state: Courier::Models::journey_state,
        ?request_options: Courier::request_opts
      ) -> Courier::JourneyResponse

      def retrieve: (
        String template_id,
        ?version: String,
        ?request_options: Courier::request_opts
      ) -> Courier::JourneyResponse

      def list: (
        ?cursor: String,
        ?version: Courier::Models::JourneyListParams::version,
        ?request_options: Courier::request_opts
      ) -> Courier::JourneysListResponse

      def archive: (
        String template_id,
        ?request_options: Courier::request_opts
      ) -> nil

      def cancel: (
        cancel_journey_request: Courier::Models::cancel_journey_request,
        ?request_options: Courier::request_opts
      ) -> Courier::Models::cancel_journey_response

      def invoke: (
        String template_id,
        ?data: ::Hash[Symbol, top],
        ?profile: ::Hash[Symbol, top],
        ?user_id: String,
        ?request_options: Courier::request_opts
      ) -> Courier::JourneysInvokeResponse

      def list_versions: (
        String template_id,
        ?request_options: Courier::request_opts
      ) -> Courier::JourneyVersionsListResponse

      def publish: (
        String template_id,
        ?version: String,
        ?request_options: Courier::request_opts
      ) -> Courier::JourneyResponse

      def replace: (
        String template_id,
        name: String,
        nodes: ::Array[Courier::Models::journey_node],
        ?enabled: bool,
        ?state: Courier::Models::journey_state,
        ?request_options: Courier::request_opts
      ) -> Courier::JourneyResponse

      def initialize: (client: Courier::Client) -> void
    end
  end
end
