module Courier
  module Resources
    class Lists
      attr_reader subscriptions: Courier::Resources::Lists::Subscriptions

      def retrieve: (
        String list_id,
        ?request_options: Courier::request_opts
      ) -> Courier::List

      def update: (
        String list_id,
        name: String,
        ?preferences: Courier::Lists::RecipientPreferences?,
        ?request_options: Courier::request_opts
      ) -> nil

      def list: (
        ?cursor: String?,
        ?pattern: String?,
        ?request_options: Courier::request_opts
      ) -> Courier::Models::ListListResponse

      def delete: (
        String list_id,
        ?request_options: Courier::request_opts
      ) -> nil

      def restore: (
        String list_id,
        ?request_options: Courier::request_opts
      ) -> nil

      def initialize: (client: Courier::Client) -> void
    end
  end
end
