module Courier
  module Resources
    class Messages
      def retrieve: (
        String message_id,
        ?request_options: Courier::request_opts
      ) -> Courier::Models::MessageRetrieveResponse

      def list: (
        ?archived: bool?,
        ?cursor: String?,
        ?enqueued_after: String?,
        ?event: String?,
        ?list: String?,
        ?message_id: String?,
        ?notification: String?,
        ?provider: ::Array[String?],
        ?recipient: String?,
        ?status: ::Array[String?],
        ?tag: ::Array[String?],
        ?tags: String?,
        ?tenant_id: String?,
        ?trace_id: String?,
        ?request_options: Courier::request_opts
      ) -> Courier::Models::MessageListResponse

      def cancel: (
        String message_id,
        ?request_options: Courier::request_opts
      ) -> Courier::MessageDetails

      def content: (
        String message_id,
        ?request_options: Courier::request_opts
      ) -> Courier::Models::MessageContentResponse

      def history: (
        String message_id,
        ?type: String?,
        ?request_options: Courier::request_opts
      ) -> Courier::Models::MessageHistoryResponse

      def initialize: (client: Courier::Client) -> void
    end
  end
end
