module Courier
  module Resources
    class Notifications
      attr_reader checks: Courier::Resources::Notifications::Checks

      def create: (
        notification: Courier::NotificationTemplatePayload,
        ?state: Courier::Models::NotificationTemplateCreateRequest::state,
        ?request_options: Courier::request_opts
      ) -> Courier::NotificationTemplateGetResponse

      def retrieve: (
        String id,
        ?version: String,
        ?request_options: Courier::request_opts
      ) -> Courier::NotificationTemplateGetResponse

      def list: (
        ?cursor: String?,
        ?event_id: String,
        ?notes: bool?,
        ?request_options: Courier::request_opts
      ) -> Courier::Models::NotificationListResponse

      def archive: (String id, ?request_options: Courier::request_opts) -> nil

      def list_versions: (
        String id,
        ?cursor: String,
        ?limit: Integer,
        ?request_options: Courier::request_opts
      ) -> Courier::NotificationTemplateVersionListResponse

      def publish: (
        String id,
        ?version: String,
        ?request_options: Courier::request_opts
      ) -> nil

      def put_content: (
        String id,
        content: Courier::NotificationContentPutRequest::Content,
        ?state: Courier::Models::notification_template_state,
        ?request_options: Courier::request_opts
      ) -> Courier::NotificationContentMutationResponse

      def put_element: (
        String element_id,
        id: String,
        type: String,
        ?channels: ::Array[String],
        ?data: ::Hash[Symbol, top],
        ?if_: String,
        ?loop_: String,
        ?ref: String,
        ?state: Courier::Models::notification_template_state,
        ?request_options: Courier::request_opts
      ) -> Courier::NotificationContentMutationResponse

      def put_locale: (
        String locale_id,
        id: String,
        elements: ::Array[Courier::NotificationLocalePutRequest::Element],
        ?state: Courier::Models::notification_template_state,
        ?request_options: Courier::request_opts
      ) -> Courier::NotificationContentMutationResponse

      def replace: (
        String id,
        notification: Courier::NotificationTemplatePayload,
        ?state: Courier::Models::NotificationTemplateUpdateRequest::state,
        ?request_options: Courier::request_opts
      ) -> Courier::NotificationTemplateGetResponse

      def retrieve_content: (
        String id,
        ?version: String,
        ?request_options: Courier::request_opts
      ) -> Courier::Models::notification_retrieve_content_response

      def initialize: (client: Courier::Client) -> void
    end
  end
end
