module Courier
  module Resources
    class Requests
      def archive: (
        String request_id,
        ?request_options: Courier::request_opts
      ) -> nil

      def initialize: (client: Courier::Client) -> void
    end
  end
end
