module Courier
  module Resources
    class Send
      def message: (
        message: Courier::SendMessageParams::Message,
        ?request_options: Courier::request_opts
      ) -> Courier::Models::SendMessageResponse

      def initialize: (client: Courier::Client) -> void
    end
  end
end
