module Courier
  module Resources
    class Send
      def send_message: (
        message: Courier::Models::message,
        ?request_options: Courier::request_opts
      ) -> Courier::Models::SendSendMessageResponse

      def initialize: (client: Courier::Client) -> void
    end
  end
end
